### ISSUE TITLE
Necessity of editing $PATH

### ISSUE THREAD

**Issue by ReGuess** [bbolli/tumblr-utils#103]
Is it really necessary for users – especially Windows users – to edit their $PATH variables? The Windows operating system checks the current working directory before it checks %PATH%, and the beginner's instructions tell the user how to cd to the right directory before running tumblr_backup.py, so it seems like having the user edit %PATH% creates an unnecessary security risk.

**Comment by bbolli** [comment]
What's the risk exactly? Other tools add their install folder to the PATH all the time.

But feel free to send a pull request to remove the offending instructions.

**Comment by ReGuess** [comment]
https://security.stackexchange.com/questions/143288/some-folders-in-the-path-variable-are-writable-by-anyone-dangerous-or-not

**Comment by Cebtenzzre** [comment]
Editing PATH is a normal thing for a user to do. It can only affect the behavior of poorly written programs or the command line.
