### ISSUE TITLE
Index.html shows nothing but blog description.

### ISSUE THREAD

**Issue by keepyoursecrets** [bbolli/tumblr-utils#107]
Not sure whats happened as this was working without error the other day, i tried back up a blog today and it went fine as usual, images, posts etc have been saved but when i clicked the index.html all i could see was the tumblr description. No posts like i normally could.

So i decided to try another i know i backed up last week and was fine, only this time again the index.html did nothing. 

I'm not sure how or even if i could change anything. Anyone having this problem?

**Comment by bbolli** [comment]
Can you try to rebuild index.html with `tumblr_backup.py -n1`?

**Comment by keepyoursecrets** [comment]
> Can you try to rebuild index.html with `tumblr_backup.py -n1`?

It seems a week later its working again fine? maybe it was a tumblr internal issue?

**Comment by bbolli** [comment]
I have no idea.
