### ISSUE TITLE
"WARNING: Falling back on generic information extractor."

### ISSUE THREAD

**Issue by jjjoe** [bbolli/tumblr-utils#108]
Apologies, this is the first Python thing I've ever used. I can get this basically working (download HTML and images) but for video/audio I encountered a problem, possibly.

I followed the directions in https://github.com/bbolli/tumblr-utils/issues/70#issuecomment-175198380, then went to command line and did `tumblr_backup.py --save-video --save-audio --skip-images [blogname]`

It gives me
`WARNING: Falling back on generic information extractor.`
over and over again while working the task.

I don't know if perhaps the difference between files/folders named "youtube-dl" and "youtube_dl" is the main issue, or if I've just done something wrong.

However, it **is** downloading MP4s, WEBMs, MP3s, and MOV.

**Comment by bbolli** [comment]
I think this is just a diagnostic message from youtube-dl. I don't know if it can be suppressed.
