### ISSUE TITLE
Wish: navigate via tags

### ISSUE THREAD

**Issue by larissakumo** [bbolli/tumblr-utils#109]
First, thanks so much for this tool! I've been looking for something like this for years. Also appreciate the beginner's guide as I don't use the command line very often.

Anyway, I noticed in the backup that all the tags linked to Tumblr, and I'm wondering if it's possible to make offline tag pages? (e.g. yourblog.tumblr.com/tagged/subject) I can find my posts by date, but I use tags to organize them, and it'd be nice to have it work as a completely offline archive. Extra nice if they can be sorted either chronologically or latest post first.

If this isn't feasible at all with tumblr's API, feel free to disregard this! Just thought I'd ask.

**Comment by larissakumo** [comment]
I was thinking basically an offline version of the page - basically navigating by tag rather than by date. For instance, [this](https://staff.tumblr.com/tagged/Week-in-Review) is one of the tags on Tumblr's staff blog. Currently you'd only be able to see those posts if you found them in each month's archive - I'm looking for separate pages to just see that.

**Comment by bbolli** [comment]
It's certainly possible to generate more than one index, but I haven't had the need yet. If anybody wants to implement this, I'm open for a pull request.

**Comment by martiniandolive** [comment]
A way to navigate tags offline would be HUGELY useful. This tool is great, but it's hard to find a specific post I'm looking for without tags.

**Comment by bbolli** [comment]
I'm going to try to implement this tonight. Please stand by...
