### ISSUE TITLE
on a macbook - alternative?

### ISSUE THREAD

**Issue by derrierebender** [bbolli/tumblr-utils#111]
Hi! I wanted to run this in order to save all my tumblr data but unfortunately I only have an old macbook air I am using. Is there a way/alternative to still run the code and if so could you direct me to instructions/another post? Thanks!

**Comment by different55** [comment]
It works fine on a macbook just install python2.

**Comment by derrierebender** [comment]
i think I had it on the wrong setting. I'll try it again later. thanks!!!

**Comment by l3112** [comment]
Everything is the same except the path will look differently.

**Comment by BryanWB88** [comment]
I keep inputting variations on “cp ~MacintoshHD/Users/*username*/Desktop/TUMBLRARCHIVE/tumblr-utils-master”…

Then “python tumblr_backup.py *tumblrname*”…

…and I keep getting “MacOS/Python: can't open file 'tumblr_backup.py': [Errno 2] No such file or directory”.

I’m a complete newbie at coding.  What am I doing wrong?

**Comment by l3112** [comment]
Are you trying to change the directory? That's cd
& you probably don't have to do all of that (If you're the only person logged into the Macbook, I mean) with that long path.
Put the file in Documents, go to the terminal, and type in
cd Documentscd (folder name bc I don't remember what it is)
then python tumblr_backup.py 

    On Monday, December 3, 2018, 8:49:18 PM CST, BryanWB88 <notifications@github.com> wrote:  
 
 
I keep inputting variations on “cp ~MacintoshHD/Users/username/Desktop/TUMBLRARCHIVE/tumblr-utils-master”…

Then “python tumblr_backup.py tumblrname”…

…and I keep getting “MacOS/Python: can't open file 'tumblr_backup.py': [Errno 2] No such file or directory”.

I’m a complete newbie at coding. What am I doing wrong?

**Comment by BryanWB88** [comment]
> Everything is the same except the path will look differently. You open the terminal and when it comes to running the program, the phrase is python tumblr_backup.py [blogname]
> 
> ![screen shot 2018-12-03 at 8 24 29 pm](https://user-images.githubusercontent.com/45317033/49414811-4c981800-f73a-11e8-8fa9-d6e8d65a9d83.png)

I keep inputting variations of “cp ~MacintoshHD/Users/username/Desktop/TUMBLRARCHIVE/tumblr-utils-master” into Terminal…

Then “python tumblr_backup.py tumblrname”…

…and I keep getting “MacOS/Python: can't open file 'tumblr_backup.py': [Errno 2] No such file or directory”.

I’m a complete newbie at coding. What am I doing wrong?

**Comment by BryanWB88** [comment]
EDIT: Sorry, deleted my comment because it occurred to me that I maybe should start a new issue, then I saw your response.

I keep inputting variations of “cp ~MacintoshHD/Users/username/Desktop/TUMBLRARCHIVE/tumblr-utils-master” into Terminal…

Then “python tumblr_backup.py tumblrname”…

…and I keep getting “MacOS/Python: can't open file 'tumblr_backup.py': [Errno 2] No such file or directory”.

I’m a complete newbie at coding. What am I doing wrong?

**Comment by BryanWB88** [comment]
Thank you.  I had to try a few different variations of the first code, but I finally got results with "cd Documents/TUMBLRARCHIVE/tumblr-utils-master” and then “python tumblr_backup.py tumblrname”.
