### ISSUE TITLE
Re: Deleted Posts

### ISSUE THREAD

**Issue by ClericBob** [bbolli/tumblr-utils#112]
Hello, I'm sorry to ask this question in this manner, but how does the backup script deal with posts that are deleted?  With all the hullabaloo going on on Tumblr right now, I want to be sure that if I have an automatic backup, it won't delete any posts that are gone on the server side.  Thanks!

**Comment by nightpool** [comment]
it depends on how your automatic backup is set up. Incremental backups only download posts that are more recent then the most recently seen post, so nothing older will get deleted

**Comment by ClericBob** [comment]
Thank you for your prompt reply
Just to be clear, is an incremental or a full backup the inferred default when no argument is specified?

**Comment by bbolli** [comment]
Incremental backup is enabled with `-i` or if the hour of `-a=HH` doesn't match. If run without arguments, it does a full backup.
