### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by shade6116** [bbolli/tumblr-utils#116]
I'm a total newbie who's trying to backup my tumblrs, but so far when I follow your instructions on the the program, when I do the Command Line thing it just spits out "bbolli tumblr... is not recognized as an internal or external command, operable program or batch file." What do I do?

**Comment by Hrxn** [comment]
Make sure that you have actually a working Python 2.x first..

**Comment by sanaeeh** [comment]
I've got exactly the same problem as _shade6116_ (and I am as well a newbie... I tried Following the instructions but I am stuck at the same step...)
I got this message (which mean that bb[...] is not recognized as an internal or extern command, an executable program, or command file). Can anyone explain what the problem is?   
<img width="388" alt="croquis 1" src="https://user-images.githubusercontent.com/45610132/49477204-84778c00-f81c-11e8-9bec-dfbe25a9bfd7.png">

**Comment by adamamyl** [comment]
from the screen shot, it _looks_ like you're not starting it with `python ` at the front. Or using the script name (`tumblr_backup.py`).

Does https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup_for_beginners.md help?

**Comment by bbolli** [comment]
Please don't blank out the important stuff! I need to see the whole command line you enter.

**Comment by sanaeeh** [comment]
no it is not python... I can not make it work... so I am using the command line of my computer... Maybe that's my problem? (But I downloaded the latest v.2 of python (Windows x86 MSI installer) and I can not go further than this)
![huhd](https://user-images.githubusercontent.com/45610132/49478089-239d8300-f81f-11e8-8b5f-2bde366284a4.png)
(and the part that I blank out was just my name)

**Comment by bbolli** [comment]
You have started Python without giving it the script file name as argument. The complete command is `python tumblr_backup.py <blog-name>`, assuming you have changed directory into the folder where the script is saved.

**Comment by sanaeeh** [comment]
okay... What does that mean? Should I uninstall and install it again? I have to put that command somewhere?
(I am really sorry that is the first time I do Something like that ...)

**Comment by bbolli** [comment]
Please follow the beginner's guide. I have just updated it a bit.

**Comment by bbolli** [comment]
The errors come from the `@` character. You're supposed to just enter the blog name.

**Comment by sanaeeh** [comment]
ah... is it going to be a problem? Do I have to stop it? Or is it working anyway?

**Comment by bbolli** [comment]
No, just let it run.

**Comment by sanaeeh** [comment]
Ok! Thank you very much! I will see if it works in the end !
Again, sorry for my lack of knowledge in the area and Thanks for your time!

**Comment by bbolli** [comment]
No problem! Glad you like it...

**Comment by sanaeeh** [comment]
It worked! Thank you so much!!! \o/ (now, bed time!)
