### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by thrwway1506** [bbolli/tumblr-utils#119]
I am getting this error when I run python2 tumblr_backup.py yetanotherstalker in terminal, I am on OSX.

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> getting https://api.tumblr.com/v2/blog/yetanotherstalker.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1

Could anyone help?

**Comment by Hrxn** [comment]
Try it with the latest version of Python (2.x)..

**Comment by thrwway1506** [comment]
I am using 2.7.15

**Comment by bbolli** [comment]
Try with option `--no-ssl-verify`.

**Comment by thrwway1506** [comment]
That worked. Thank you very much!
