### ISSUE TITLE
Using youtube_dl on mac os x

### ISSUE THREAD

**Issue by bs785** [bbolli/tumblr-utils#120]
I successfully downloaded my tumblr likes (text, photo), but now I'm trying to download audio and video as well, but I'm stuck at the following error: 
tumblr_backup.py: error: --save-video/-audio: module 'youtube_dl' is not installed 

I found [this ](https://github.com/bbolli/tumblr-utils/issues/89) and redownloaded youtube-dl using pip, but I got that same error again. I'm still a relative newbie to command line stuff so I'm not sure where I'm going wrong/how to fix it, so any help would be appreciated.

I'm on os x 10.11 and I'm using python 2.7. Thanks in advance!

**Comment by adamamyl** [comment]
It might be worth checking youtube-dl _is_ installed. I'd go for the approach mentioned in the issue linked, but it might be good to see if the expected directory exists/has files:

`ls /Library/Python/2.7/site-packages/youtube_dl` should give some output.

If not, then try `pip install youtube-dl` (or `pip install --upgrade youtube_dl`).

**Comment by bs785** [comment]
Ah turned out it wasn't actually installed! I installed it correctly following the second method in the linked issue and got the posts downloaded. Thanks!
