### ISSUE TITLE
--save-videos keeps giving me corrupt videos... 

### ISSUE THREAD

**Issue by TMTTMTTMT** [bbolli/tumblr-utils#121]
the videos either not work completely, or they get corrupt, most of the time they reach 2.5 MB and just stop right there. 

does it have to do with timeout or something? I have no idea how to proceed to fix this issue

**Comment by Cebtenzzre** [comment]
This isn't enough information to reproduce this issue. What blog? What OS? What version/commit of tumblr-utils? Are these Tumblr videos or external embeds? Too bad this issue predates the tempate...
