### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by estherflails** [bbolli/tumblr-utils#122]
It might just be because I did something wrong, but I cannot find where the backup is downloaded to.  I put the program in C:\bbolli-tumblr-utils-f234953 but no new folders are created there to facilitate the download. The download is done, because when I try to redownload its done quickly as there is nothing new to add (I assume, at least), but I cannot find where the downloads end up.

(On a different note, your download link to pyexiv2 doesn't work, so this is where I got it from: https://launchpad.net/pyexiv2/+download)

**Comment by Hrxn** [comment]
The default location is always the currently active directory when running the program, also known as <abbr title="Current Working Directory">CWD</abbr>.

There should be a sub-directory called *<blog-name>* (like in the Tumblr URL part) in there.

Unless you specified the `--outdir=OUTDIR` option when running tumblr_backup.

**Comment by estherflails** [comment]
"Currently active directory" means the same folder as the file tumblr_backup.py is in, right? I did not specify `--outdir=OUTDIR`, but the sub-directory is not there.

**Comment by bbolli** [comment]
Please post a screen shot of the output.

**Comment by estherflails** [comment]
[Here you go.](https://www.dropbox.com/s/2znnecyqw4wrtqv/Screenshot%202018-12-04%2023.56.22.png?dl=0) I wasn't sure which "output" you meant, but the folder is empty except for the files that came with the program and cmd output just says that it's done and it supposedly worked.

**Comment by bbolli** [comment]
BTW you can drag images into comments here; no need to put them on DropBox.

Your active directory is C:\WINDOWS\system32, as can be seen in the prompt. Your tumblr is saved inside this folder.

There's no need to run the backup as Administrator; doing so just increases the chance of breaking something.

**Comment by estherflails** [comment]
Thank you, found it! :) I forgot I was running it as Administrator, I'll keep that in mind. Thanks again! :)
