### ISSUE TITLE
Exporting posts passed "Read More"/"Keep Reading"

### ISSUE THREAD

**Issue by VaultLink** [bbolli/tumblr-utils#125]
Is there the ability to or going to be an option in the future to download posts passed "Read More"/"Keep Reading"?

**Comment by bbolli** [comment]
Do you have an example?

**Comment by VaultLink** [comment]
http://saving-dreemurr.tumblr.com/post/160525352465/floweys-ability-to-feel

**Comment by bbolli** [comment]
Ouch! That's a reblog, so I assume the reblogged post only contains the content up to the fold. I see no way of handling this automatically.

**Comment by VaultLink** [comment]
I know basically nothing. Could it possible jump over using the link in the "Keep Reading" grab whats needed from that post and stitch it in? I'm looking at some other posts with it and I could see problems with this tho if someone had put their own "Keep Reading" link into a post.

**Comment by Cebtenzzre** [comment]
This is just a cut reblog with an HTML link to the original post. The link was inserted by the author and is not a directly supported feature of Tumblr, so it's not really possible to reliably parse this.
Downloading the blog `nochocolate` should include the original post, so I don't see anything that would need to be changed in tumblr-utils to let you read these posts in a backup.
