### ISSUE TITLE
Which path?

### ISSUE THREAD

**Issue by sspice** [bbolli/tumblr-utils#127]
While I was following your instructions, I got as far as the Advanced System Settings/Environment Variables. However I'm not entirely sure which Path variable I'm supposed to choose, as my desktop computer has one for the username I'm logged on under and one for the system.

I'd greatly appreciate a little more clarity, and hope to hear from you soon.

**Comment by Hrxn** [comment]
Both would work. But use the one for the User.

**Comment by sspice** [comment]
All right. I've just entered what the instructions told me to enter for Command Prompt (python tumblr_backup.py yourtumblrname), but all I'm getting is "'python' is not recognized as an internal or external command, operable program or batch file.

Python is installed, but I'm still fairly new to it, so I'm not sure what to do next.
