### ISSUE TITLE
Cant get over syntax error

### ISSUE THREAD

**Issue by Tsukifox** [bbolli/tumblr-utils#129]
evrything else works except this part where you have to type (python tumblr_backup.py username) it just says syntax error but everything is written correctly

**Comment by Tsukifox** [comment]
thanks but already tried that, still same result.
I also added both paths just in case, the location where the tumblr files are and the Python location.
Still syntax error. What username should I type in there? Just my current username?

**Comment by bbolli** [comment]
Please post a screen shot of what you enter and the error message.

**Comment by Tsukifox** [comment]
![dddaw](https://user-images.githubusercontent.com/45614660/49553643-59457900-f8be-11e8-99cf-3cac27c82471.JPG)
this is the error

**Comment by Cebtenzzre** [comment]
What's the output of `python --version`?

**Comment by Tsukifox** [comment]
My version of python is 2.2

**Comment by Tsukifox** [comment]
Holy shit haha yeah its working now, thank you cebtenzzre!
