### ISSUE TITLE
Error 404 Not Found Using Api

### ISSUE THREAD

**Issue by cstadlock** [bbolli/tumblr-utils#130]
Upon entering this into my cmd line I receive an error that I can't seem to be able to solve.

C:\Users\Username\Documents\bbolli-tumblr-utils-c63cbd8>python2 tumblr_backup.py MyTumblrUsername

I receive the error:
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/MyTumblrUsername.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
This Error Over and Over

**
Note: I have python 2.7.15 & 3.7.1 on my computer and they can be run selectively by using python2 or python3 so this should not be the cause of the error. I also so a similar issue that has already been answered here: https://github.com/bbolli/tumblr-utils/issues/119 but I attempted to add --no-ssl-verify to the end with no change unless I'm doing this wrong.
Example:
C:\Users\Username\Documents\bbolli-tumblr-utils-c63cbd8>python2 tumblr_backup.py MyTumblrUsername --no-ssl-verify
**

Any help would be greatly appreciated thanks.

**Comment by vlur** [comment]
Verify the spelling of `MyTumblrUsername` and make sure it is a blog that exists.

**Comment by cstadlock** [comment]
I simply changed that just for privacy but yes the name is 100% accurate so what I have entered is 
C:\Users\[Private]\Documents\bbolli-tumblr-utils-c63cbd8>python2 tumblr_backup.py [SpelledCorrectly]

But I still get the same error. 
![error1](https://user-images.githubusercontent.com/22641174/49489440-ee8e3200-f818-11e8-88d7-226ac724430c.PNG)
![erro2](https://user-images.githubusercontent.com/22641174/49489441-ee8e3200-f818-11e8-9503-fbbaa8e6f52f.PNG)

It stays at the first image for like 1 second then goes to the all the errors shown in the second image.

**Comment by cstadlock** [comment]
I figured out the problem its all solved now :) but for anyone who may run into this issue make sure to check your settings and have this off. 
![sol](https://user-images.githubusercontent.com/22641174/49489787-96582f80-f81a-11e8-86b5-7edf2fd270d0.PNG)

**Comment by kafuku1** [comment]
What can I do if I want to backup others' people blog that are set to private?

**Comment by Cebtenzzre** [comment]
@kafuku1 Use [TumblThree](https://github.com/johanneszab/TumblThree) for now.  Maybe it'll be supported here someday, see #128.
