### ISSUE TITLE
Error when using --save-video/-audio option

### ISSUE THREAD

**Issue by SigEpBlue** [bbolli/tumblr-utils#134]
I'm getting the following error:
`tumblr_backup.py: error: --save-video/-audio: module 'youtube_dl' is not installed
`
But in fact, I have had youtube-dl installed, and have been using it regularly, for years.

Is it possible the program is looking for 'youtube_dl' instead of 'youtube-dl'?

**Comment by SigEpBlue** [comment]
Oohkay, now I feel silly. Thank you so much for the details, @vlur ! I didn't realize there were different versions, but it makes sense now. I used pip, imported as the post to which you linked described, and I'm good now.

Thanks again! :)

**Comment by vlur** [comment]
Hey, no problem @SigEpBlue :) No need to feel silly. Glad it helped and glad you got it working!
