### ISSUE TITLE
--save-audio not actually saving local copies

### ISSUE THREAD

**Issue by vlur** [bbolli/tumblr-utils#136]
This might also occur with `--save-video` but I have not tested.

When saving posts and using the `--save-audio` option, tumblr_backup.py runs without complaint and downloads the blog posts successfully, but no mp3s are downloaded to the `media` directory. Instead, audio embeds in the saved html posts still link to Tumblr content, e.g. :

```html
<article class=audio id=....>
<header>
<p><time datetime=2018-12-05>12/5/2018 00:00:00 AM</time>
<a class=llink href=../posts/%somenumber%.html>¶</a>
<a href=https://tmblr.co/%somelink%●</a></header>
<iframe class="tumblr_audio_player tumblr_audio_player_%somenumber%" src="https://MyTumblrBlog.tumblr.com/post/%somenumber%/audio_player_iframe/MyTumblrBlog/tumblr_blahblahblahblah?audio_file=https%3A%2F%2Fa.tumblr.com%2Ftumblr_blahblahblahblah.mp3" frameborder="0" allowtransparency="true" scrolling="no" width="540" height="169"></iframe>
```

What am I doing wrong?

**Comment by bbolli** [comment]
It's possible that the heuristic at https://github.com/bbolli/tumblr-utils/blob/ac333b0b042d4bc0a91fbe89e21ea7e19d3dcc3a/tumblr_backup.py#L671 doesn't work anymore. Can you post (in a comment here) the JSON file of your audio post?

**Comment by bbolli** [comment]
Thanks; that's going to be an easy fix!
