### ISSUE TITLE
Request: Initiate downloads of Tumblr Blogs being followed

### ISSUE THREAD

**Issue by omque** [bbolli/tumblr-utils#137]
Thank you so much for this - I came here via the comment you made on the Verge.

I was wondering if for a future version there was a way to add have the program detect which blogs I am following via https://www.tumblr.com/following and initiate a backup process for the blogs that are listed there?

**Comment by bbolli** [comment]
Thanks; the comment wasn't from me, but anyway...

You can give more than one blog name on the command line (that's what the `...` in the docs indicate), so I don't see a need for auto-downloading blogs you follow.

**Comment by omque** [comment]
Thanks for the clarification! 

The reason I was suggesting a way to automate was because I have about 60 blogs that I follow that I'd like to not spend manually entering into a command line. Not sure if that was possible with the current version.

**Comment by Cebtenzzre** [comment]
@omque Use https://www.tumblr.com/following.opml and xmlstarlet (`xmlstarlet sel -t -m '/opml/body/outline' -v @htmlUrl -n`) if you want the complete list, including some deleted/deactivated blogs.  This method may not work if you follow a lot of blogs.

Another approach, which gets you a plain text file more easily, is [RetroRodent/tumblrfollows](https://github.com/RetroRodent/tumblrfollows).

**Comment by omque** [comment]
Thanks! This is just what I needed!
