### ISSUE TITLE
Reblogged posts

### ISSUE THREAD

**Issue by kafuku1** [bbolli/tumblr-utils#139]
In the current state you cannot see from which blog the post are reblogged from. I'd like to see that since often the source of the post is missing and you're left with no information at all.

**Comment by Cebtenzzre** [comment]
As far as I understand, the reblog information _is_ saved if you specify the `-j` option, though it's in raw JSON format only.  I skimmed it and it seems to include the whole "trail" of reblogs for each post.
As long as you have that it can feasibly be parsed and displayed someday.
