### ISSUE TITLE
The tag index doesn't link properly to tags with umlauts or other non-ASCII characters

### ISSUE THREAD

**Issue by bbolli** [bbolli/tumblr-utils#140]
Need to percent-escape the percent signs in the link's href.

**Comment by ecm-pushbx** [comment]
Here's a patch which improves the situation. Tested with a blog at http://ecm-pushbx.tumblr.com/

The first quote_plus call is to escape slashes into %2F in the filename. It's somewhat of a hack, since we want to escape slashes but not double-escape already escaped bits (hence `safe='%'`).

The second bit is replacing %2F in the escaped href link into %252F (escaped percent sign and then use that to escape a slash), which was necessary to make it work in my browser (Firefox 60.3.0esr).

The third bit is escaping the href link. Not sure whether this is actually needed.

The last bit is not escaping the link title. Without this, the less-than sign, three sequence in a tag is written into the HTML source as "&amp;lt;3" which is doubly escaped. Dropping the escape call there results in "&lt;3" in the HTML source and renders as "<3" correctly.

```
diff --git a/tumblr_backup.py b/tumblr_backup.py
index bdbf839..f18f293 100755
--- a/tumblr_backup.py
+++ b/tumblr_backup.py
@@ -415,11 +415,13 @@ class Indices:
         self.fixup_media_links()
         tag_index = [self.blog.header('Tag index', 'tag-index', self.blog.title, True), '<ul>']
         for tag, index in sorted(self.tags.items(), key=lambda kv: kv[1].name):
-            index.save_index(tag_index_dir + os.sep + tag,
+            index.save_index(tag_index_dir + os.sep + urllib.quote_plus(tag.encode('utf-8'), safe='%'),
                 u"Tag ‛%s’" % index.name
             )
             tag_index.append(u'    <li><a href=%s/%s>%s</a></li>' % (
-                tag, dir_index, escape(index.name)
+                re.sub('%2F', '%252F',
+                    urllib.quote_plus(tag.encode('utf-8'), safe='')),
+                dir_index, index.name
             ))
         tag_index.extend(['</ul>', ''])
         with open_text(tag_index_dir, dir_index) as f:
```

**Comment by aylamar** [comment]
ecm-pushbx's fix worked for me. The only kind of tags that I've encountered issues with since applying the fix are tags that end in periods. Tags that end in periods cause tumblr_backup.py to error out just like it would with tags that contained non-ASCII characters.

**Comment by angelbots** [comment]
How do I install this patch? Apologies, I am unfamiliar with python and thanks.

**Comment by ecm-pushbx** [comment]
> How do I install this patch? Apologies, I am unfamiliar with python and thanks.

Hard way: https://www.google.com/search?q=how+to+apply+patch

Easy way: Wait for the maintainer to apply this or a similar patch, then update or re-install the program.

**Comment by ecm-pushbx** [comment]
> ecm-pushbx's fix worked for me. The only kind of tags that I've encountered issues with since applying the fix are tags that end in periods. Tags that end in periods cause tumblr_backup.py to error out just like it would with tags that contained non-ASCII characters.

Thanks for testing. Are you running the script on MS Windows? I think filenames ending in a dot aren't allowed there. Not sure about my setup (ext4 on Debian), can test it though.

**Comment by ecm-pushbx** [comment]
On my girlfriend's Debian server (I'm not at home right now) the tags ending in a dot seem to be saved and linked correctly.

**Comment by ecm-pushbx** [comment]
As I cannot, someone with an MS Windows box should try whether they can escape (any or only trailing) dots in the links and filenames.

**Comment by aylamar** [comment]
> Thanks for testing. Are you running the script on MS Windows? I think filenames ending in a dot aren't allowed there. Not sure about my setup (ext4 on Debian), can test it though.

No problem and that's right! I'm running Windows 10. Worst case if this isn't patched in the next few days, I'll just run tumblr-utils on an Ubuntu VM and skip transferring over the folders with trailing dots. On another note, it's only trailing dots that cause errors on Windows 10 from my experience. Windows 10 is fine with dots in the folder and file name as long as they're not trailing.

**Comment by gromgit** [comment]
@ecm-pushbx 's patch also resolves a related and far-more-common issue: _tags with embedded spaces_. Tag directories are created with URL-encoded spaces (i.e. `tags/My%20Tag%20Here/`), but before this patch, the URLs in the tag HTML files literally used the same pathname (i.e. `My%20Tag%20Here/index.html`), causing the web server to look for the nonexistent pathname `tags/My Tag Here/index.html`.

**Comment by ecm-pushbx** [comment]
> No problem and that's right! I'm running Windows 10. Worst case if this isn't patched in the next few days, I'll just run tumblr-utils on an Ubuntu VM and skip transferring over the folders with trailing dots. On another note, it's only trailing dots that cause errors on Windows 10 from my experience. Windows 10 is fine with dots in the folder and file name as long as they're not trailing.

Yes, that's why I wrote "filenames ending in a dot".

Here's a new revision of my patch (to be applied to the repo as is, without applying the earlier patch -- it is included in this one too). Please check whether this correctly links to and stores tag pages of tags ending in a dot on MS Windows; it should, but I can't test it there.

```
diff --git a/tumblr_backup.py b/tumblr_backup.py
index bdbf839..aea1aba 100755
--- a/tumblr_backup.py
+++ b/tumblr_backup.py
@@ -415,11 +415,19 @@ class Indices:
         self.fixup_media_links()
         tag_index = [self.blog.header('Tag index', 'tag-index', self.blog.title, True), '<ul>']
         for tag, index in sorted(self.tags.items(), key=lambda kv: kv[1].name):
-            index.save_index(tag_index_dir + os.sep + tag,
+            index.save_index(tag_index_dir + os.sep +
+                             re.sub('\.$', '%2E',
+                                    urllib.quote_plus(tag.encode('utf-8'), safe='%')
+                                    ),
                 u"Tag ‛%s’" % index.name
             )
             tag_index.append(u'    <li><a href=%s/%s>%s</a></li>' % (
-                tag, dir_index, escape(index.name)
+                re.sub('\.$', '%252E',
+                    re.sub('%2F', '%252F',
+                        urllib.quote_plus(tag.encode('utf-8'), safe='')
+                        )
+                    ),
+                dir_index, index.name
             ))
         tag_index.extend(['</ul>', ''])
         with open_text(tag_index_dir, dir_index) as f:
```

**Comment by ecm-pushbx** [comment]
There's another problem: Tags that differ only in how their text is capitalised, will probably fail somehow on MS Windows, or otherwise on filesystems that are cap-insensitive.
