### ISSUE TITLE
CMD Prompt returning error

### ISSUE THREAD

**Issue by dethcrow** [bbolli/tumblr-utils#143]
When trying to run the backup, command prompt is only returning an error reading:

'python' is not recognized as an internal or external command, operable program, or batch file.

**Comment by Cebtenzzre** [comment]
Either Python is not installed, or it is not in your PATH.  The Issues page is supposed to be for real issues with the software, not technical support.  Please use Google next time.

**Comment by dethcrow** [comment]
Python is installed, and from the way the directions are written, I've added it to my path exactly how it's described. You don't even know if I already used Google, which I did, so the lip isn't necessary. Instead of telling me to do the first thing I tried for the two hours before I even made the post, you could actually be helpful. Also, last I checked, technical support is an issue, especially when following the directions verbatim and it not working as intended. Here's my proof for the programmer.
![evsettings](https://user-images.githubusercontent.com/45647211/49564955-bce19d80-f8e2-11e8-9b3a-2d1f2b1a9515.jpg)
![cmderror](https://user-images.githubusercontent.com/45647211/49564957-c1a65180-f8e2-11e8-8dc2-e52eec987312.jpg)
![python](https://user-images.githubusercontent.com/45647211/49564994-dbe02f80-f8e2-11e8-98f1-39a458a49bba.jpg)
