### ISSUE TITLE
Still can't get things to work

### ISSUE THREAD

**Issue by shade6116** [bbolli/tumblr-utils#146]
I've downloaded python and edited the Path environment variables (both for "User Variables for User" and "System Variables", putting a semicolon both at the end of the previous line and on the tumblr path itself). I also both put in and left out 'python' in command prompt but it's still not working for me.
![technical](https://user-images.githubusercontent.com/45599922/49588510-df9ca200-f934-11e8-83fa-05974dceaa9f.png)
I followed the instructions in this post ( http://clockpunkgamelover.tumblr.com/post/180814556438/loreweaver-universe-damaramegido ), so that's why I entered my desktop in command prompt.

**Comment by datadog23** [comment]
It looks like you haven't got python installed, maybe the installer didn't work?
When it does work, you should be able to type `where python` into a terminal and it'll give you a filename (which doesn't matter what it is, just that it exists).

**Comment by shade6116** [comment]
I used the x86 MSI installer and ran it, now when i open it, it asks change, repair, or remove.

**Comment by datadog23** [comment]
Ooo! [This Issue](https://github.com/bbolli/tumblr-utils/issues/143) suggests adding `C:\Python27` to your Path, that might be why Windows isn't finding it -- it's installing correctly, but not being made accessible.

**Comment by shade6116** [comment]
So what would be the full line to put into Path? And which Path should it be?

**Comment by datadog23** [comment]
Either Path should work: the second one would make it work for all user accounts on the system, the first one just yourself.

I'm not sure what the full line should be, it probably varies by version of Windows and what other programs you have on there. Just do the thing with appending a semicolon to the current version and then adding the new folder location to the end.

**Comment by shade6116** [comment]
Added c:\Python27; to User variables and pasted the desktop path after it. I don't think that was right since it's still not working.

**Comment by datadog23** [comment]
Does the folder c:\Python27 exist? Maybe it's being installed somewhere else...

**Comment by shade6116** [comment]
It does, it's in my Local Disk.

**Comment by datadog23** [comment]
I have no idea then, sorry.

Btw, if you type `PATH` in a terminal it should show the two Path variables concatenated, and this is what the terminal actually uses when searching for things to run, maybe check that this IS actually being updated with your edits? It's a long shot but I can't think of anything else to try.

**Comment by shade6116** [comment]
After some fiddling:
![techincal 2](https://user-images.githubusercontent.com/45599922/49597034-9efb5380-f949-11e8-917e-978123e0fff1.png)

**Comment by datadog23** [comment]
Ah! Try going along your user variable path and removing all the quotemarks -- they were probably added by your browser or text editor (assuming you were copying and pasting stuff) and are confusing the terminal.

**Comment by shade6116** [comment]
Deleted the " :
![techincal 2](https://user-images.githubusercontent.com/45599922/49598146-07e3cb00-f94c-11e8-807b-03d9d6807d57.png)

**Comment by shade6116** [comment]
It finally worked!

**Comment by datadog23** [comment]
But does it work now?

**Comment by datadog23** [comment]
Congrats!
