### ISSUE TITLE
Safe mode prevents video downloading

### ISSUE THREAD

**Issue by mcscope** [bbolli/tumblr-utils#147]
While using tumblr_backup to archive tumblrs, it seems like certain content is blocked by the Tumblr safe-mode feature.  I get a 403 on all videos.
Is there any way to enter Tumblr account information, so the safe-mode value can be read from that? 

```HTTP Error 403: Forbidden downloading <url redacted>
ERROR: This Tumblr may contain sensitive media. Disable safe mode in your account settings at https://www.tumblr.com/settings/account#safe_mode
Unable to download video in post #<redacted
```

**Comment by bbolli** [comment]
No, not at the moment. You have to disable safe mode while doing the backup.

**Comment by jhein05** [comment]
Hi Beat, I apologize if the question is stupid, but how would I do that? Thank you!

**Comment by Cebtenzzre** [comment]
@jhein05 This has nothing to do with Tumblr's API; it's an error generated by youtube-dl.  You have use a cookie file as described in #132.  "Safe mode" is the default for non-authenticated requests.
