### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by kabunevermind** [bbolli/tumblr-utils#149]
First time using python, so I'm a little over my head. I followed the instructions, but I'm getting an error in response.

![help](https://user-images.githubusercontent.com/45672282/49611865-8babb080-f968-11e8-945b-5f84b8fb4279.PNG)

Any help on how to fix this? I'm stuck.

**Comment by Hrxn** [comment]
Python version?
Run `python -V` in CMD. Or just `python`.

**Comment by kabunevermind** [comment]
3.6.5
I downloaded Python 2 so I'm not sure why it's version 3! Could that be what's causing this?

**Comment by kabunevermind** [comment]
Thank you! I've gotten this working, by uninstalling Python 3 which was strangely on my system.

**Comment by Cebtenzzre** [comment]
@kabunevermind Please make a new issue if you have any other problems with tumblr-utils.
