### ISSUE TITLE
--save-video does not work

### ISSUE THREAD

**Issue by pilaco** [bbolli/tumblr-utils#150]
I have youtube-dl installed, but when I try to download only the videos I get an error message.

`tumblr_backup.py --save-video unknown`
`Usage: tumblr_backup.py [options] blog-name ...`

`tumblr_backup.py: error: --save-video/-audio: module 'youtube_dl' is not installed`

**Comment by mcscope** [comment]
you need to install the python youtube_dl package from pip , not the command line program youtube-dl

**Comment by mcscope** [comment]
https://github.com/bbolli/tumblr-utils/issues/134

**Comment by pilaco** [comment]
> youtube-dl installed for Python 2 or Python 3?

Python 3

> you need to install the python youtube_dl package from pip , not the command line program youtube-dl

Thanks.

**Comment by Hrxn** [comment]
Make sure to use the Python 2 `pip` as well...

**Comment by mcscope** [comment]
@pilaco this is a python 2 only project I believe.

**Comment by pilaco** [comment]
I installed youtube-dl from the pip2 and it worked.
Thanks.
