### ISSUE TITLE
--tag-index not working on Windows

### ISSUE THREAD

**Issue by tavrinky** [bbolli/tumblr-utils#154]
Currently running on Windows, --tag-index straight up doesn't work

    C:\programs\tumblr-utils>C:\Python27\python.exe tumblr_backup.py --tag-index tototavros

Usage: tumblr_backup.py [options] blog-name ...

tumblr_backup.py: error: no such option: --tag-index

How do I use this option correctly? Is there any diagnostics you need (would it vary based on Windows install?)?

**Comment by Cebtenzzre** [comment]
Are you using the latest tumblr-utils?  If you downloaded it as a ZIP file, download it again.  That feature was added yesterday.
