### ISSUE TITLE
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog

### ISSUE THREAD

**Issue by kimberlycooksley** [bbolli/tumblr-utils#155]
Hi

I get the above error when trying to download my likes.
My blog is set to explicit
Thanks

**Comment by Cebtenzzre** [comment]
What is the full command you are running, and what is the full output?  If you want to remove/replace information like blog name that is fine, but more context is necessary.

**Comment by kimberlycooksley** [comment]
Cebtenzzre
Thanks for your reply. The full output (with blog name edited) is:
Also I can't use tumblr's own export function, it's greyed out.
I have been able to dnload all my posts using tumblr_backup.py, just not likes.
Thanks
bbolli-tumblr-utils-f234953 macbook$ ./tumblr_backup.py --likes --outdir=blogname-tumblr-likes -j  myblog
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog9.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 403: Forbidden getting https://api.tumblr.com/v2/blog/myblog.tumblr.com/likes?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
bbolli-tumblr-utils-f234953 macbook$

**Comment by Cebtenzzre** [comment]
Please use code tags for things like commands and command output.

**Comment by Cebtenzzre** [comment]
From what I can determine, you do not have your likes set to be publicly visible.  Unfortunately, tumblr-utils is not yet capable of saving private likes.  See issues #95, #123, and #128 (wow, there are a lot of dupes here).
