### ISSUE TITLE
Getting firewall throttled by Tumblr

### ISSUE THREAD

**Issue by cobrafast** [bbolli/tumblr-utils#158]
Bulk downloading blogs with `tumblr_backup.py` with several thousand posts eventually runs me into what I suspect is a shadow ban by Tumblr, where the media servers will no longer send any response until I wait a little while.

```text
<urlopen error [Errno 113] No route to host> downloading https://66.media.tumblr.com/***/tumblr_***_1280.jpg
```

I have written the following fish script to workaround the problem, fetching blogs in chunks of 50 posts and waiting in between.

```fish
#!/usr/bin/fish
set chunksize 50
set waittime 10
for i in (cat archivelist.txt)
        set skip 0
        set bustatus 0
        while test $bustatus -eq 0
                /home/cobra/pkg/tumblr-utils/tumblr_backup.py --save-video --save-audio -S -j -s $skip -n $chunksize $i
                set bustatus $status
                set skip (math "$skip+$chunksize")
                sleep $waittime
        end
        sleep $waittime
end
```

This now leaves me with 300 posts per minute (or 18000 posts per hour). The problem is, the threshold on Tumblr's side seems to change - when I started out I could fetch thousands of posts without any throttling, now I'm running into the sporadic "No route to host" even at 300 p/min.

I suspect this could be optimized by natively detecting this kind of error, waiting X seconds, and then trying the failed files again and continuing on until it happens again.

**Comment by Hrxn** [comment]
Do you use your own API key in `tumblr_backup.py`?

**Comment by cobrafast** [comment]
No I don't. I was not aware there was such a thing and I have not seen anything about it in any of the .md files.

**Comment by cobrafast** [comment]
I have done this mod though: https://github.com/bbolli/tumblr-utils/issues/132#issuecomment-444767677

**Comment by Hrxn** [comment]
True. In that case it is some kind of issue with the network connectivity. Some bad routes, some service outage, pester your ISP about that if necessary.

**Comment by Cebtenzzre** [comment]
"no route to host" could be a DNS issue.  Perhaps try using [Google Public DNS](https://developers.google.com/speed/public-dns/docs/using).
Or, it could be your ISP or a routing issue, as Hrxn said.  Maybe try a traceroute once you've triggered the issue?

**Comment by cobrafast** [comment]
I'm already using a local pdnsd for caching, so upstream DNS servers don't get hammered by thousands of queries for the same server. Today I managed to grab ~20k posts at full speed (~60 Mbit/s) before running into the problem.

Here's the trace when it does start to go wrong:

```text
 hots 66.media.tumblr.com
66.media.tumblr.com is an alias for cs1140.wpc.chicdn.net.
cs1140.wpc.chicdn.net has address 152.199.19.43
```

```text
 tracepath 66.media.tumblr.com
 1?: [LOCALHOST]                      pmtu 1460
 1:  _gateway                                              0.321ms
 1:  _gateway                                              0.270ms
 2:  81.210.141.226                                       13.002ms
 3:  81.210.141.225                                       13.387ms asymm  2                                                                          
 4:  de-bon01a-rd01-ae0-0.aorta.net                       17.449ms asymm 10                                                                          
 5:  de-fra04d-rc1-ae12-0.aorta.net                       25.218ms asymm  9                                                                          
 6:  de-fra04a-rc1-ae26-0.aorta.net                       19.167ms asymm  8                                                                          
 7:  de-fra03b-ri1-ae5-0.aorta.net                        15.647ms asymm  6                                                                          
 8:  ???                                                  16.052ms asymm  7                                                                          
 9:  152.195.101.129                                      21.798ms asymm  8                                                                          
10:  no reply
11:  no reply
12:  no reply
13:  no reply
14:  no reply
15:  no reply
16:  no reply
17:  no reply
^C
```

To me it looks like my ISP's side is working okay.

**Comment by Cebtenzzre** [comment]
Unless someone else can confirm this issue, I don't think it's a problem with Tumblr or tumblr-utils. No sane program should consider EHOSTUNREACH (error 113) recoverable - rate limits are expressed with HTTP status codes and unsuccessful API responses, not IP address-level routing failure.
