### ISSUE TITLE
No videos being downloaded, but no errors, and archive/post links point to remote sites

### ISSUE THREAD

**Issue by muizonline** [bbolli/tumblr-utils#160]
[ None of the open or closed issues seem to be exactly the issue I'm experiencing, although #136 mentions "--save-video may not be working either." ]

Many thanks for tumblr_backup.py. Very happy with the way it works and how quickly, however 

1) When saving posts tumblr_backup.py runs without complaint and downloads the blog posts successfully, but no mp4 files are downloaded to the media directory. 

Instead, video embeds, in the saved html posts, are linked back to Tumblr content rather than locally downloaded video files:
<pre>
&lt;article class=&quot;video&quot; id=&quot;p-179761719212&quot;&gt;
    &lt;header&gt;
        &lt;time datetime=&quot;2018-11-04T19:12:11Z&quot;&gt;11/04/2018 11:12:11&lt;/time&gt;
	&lt;a class=&quot;llink&quot; href=&quot;../posts/179761719212.html&quot;&gt;¶&lt;/a&gt;
	&lt;a href=&quot;https://tmblr.co/%characterString%&quot;&gt;●&lt;/a&gt;
    &lt;/header&gt;
    &lt;video id=&quot;embed-5c0bfe7228f2f858428070&quot;
	class=&quot;crt-video crt-skin-default&quot;
	poster=&quot;https://66.media.tumblr.com/tumblr_%characterString%_smart1.jpg&quot;
	preload=&quot;none&quot; muted=&quot;&quot;
	data-crt-video=&quot;&quot;
	data-crt-options=&quot;{&amp;quot;autoheight&amp;quot;:null,&amp;quot;duration&amp;
            quot;:48,&amp;quot;hdUrl&amp;quot;:false,&amp;quot;filmstrip&amp;quot;:
            {&amp;quot;url&amp;quot;:&amp;quot;https://78.media.tumblr.com/previews
             /tumblr_%characterString%_filmstrip.jpg&amp;quot;,&amp;quot;
            width&amp;quot;:&amp;quot;200&amp;quot;,&amp;
            quot;height&amp;quot;:&amp;quot;112&amp;quot;}}&quot; 
        width=&quot;500&quot; 
        height=&quot;281&quot;&gt;
    &lt;source src=&quot;https://%blogname%.tumblr.com/video_file/t:%characterString%&quot;
	type=&quot;video/mp4&quot;&gt;
    &lt;/video&gt;
    &lt;footer&gt;
	... various #tags, and repost source URL
    &lt;/footer&gt;
&lt;/article&gt;
</pre>

2) As an experiment running tumblr_backup.py with the "--save-video" option returns this error
<pre>
prompt$ python tumblr_backup.py --save-video %blogname%
Usage: tumblr_backup.py [options] blog-name ...

tumblr_backup.py: error: --save-video/-audio: module 'youtube_dl' is not installed
</pre>

NOTE that the error mentions "youtube_dl" because in tumblr_backup.py every mention of the youtube executable is "youtube_dl". 

That executable wasn't installed, so I searched for and found what I thought was the _underscored "youtube_dl" install command but it actually installed -hyphenated "youtube-dl" ... and of course since tumblr_backup.py is calling for the _underscored version it fails with the same file not found error.

I did find "youtube_dl 2018.12.9" at pypi.org, but the downloadable files install -hyphenated youtube-dl. There is also this terminal command "pip install youtube_dl" which when run fails with this error:
"prompt$ pip install youtube_dl
Collecting youtube-dl
  Could not find a version that satisfies the requirement youtube-dl (from versions: )
  No matching distribution found for youtube-dl"

I'm now far enough over my head that I can't go any farther. 

Hoping that a json file example from a post with a video will help with this issue, as they did for issue #136 ... here's the json file for a post that contains a video:
<pre>
{
    "blog": {
        "description": "%blogdescription%",
        "name": "%blogname%",
        "title": "%blogtitle%",
        "updated": 1544254131,
        "url": "https://%blogname%.tumblr.com/",
        "uuid": "t:Z4quGCyHJpcE67WFxo994w"
    },
    "blog_name": "%blogname%",
    "body": "<p><a href=\"https://%reblogged-root-name%.tumblr.com/post/179851904466/%slug%\" class=\"tumblr_blog\">%reblogged-root-name%</a>:</p><blockquote>\n<figure class=\"tmblr-full\" data-orig-height=\"480\" data-orig-width=\"854\" data-npf='{\"type\":\"video\",\"provider\":\"tumblr\",\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"media\":{\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"type\":\"video/mp4\",\"width\":854,\"height\":480},\"poster\":[{\"url\":\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\",\"type\":\"image/jpeg\",\"width\":854,\"height\":480}]}'><video controls=\"controls\" autoplay=\"autoplay\" muted=\"muted\" poster=\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\"><source src=\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\" type=\"video/mp4\"></source></video></figure><p class=\"npf_quote\" data-npf='{\"subtype\":\"quote\"}'>The countdown </p>\n</blockquote>",
    "can_like": false,
    "can_reblog": false,
    "can_reply": false,
    "can_send_in_message": true,
    "date": "2018-11-11 18:15:42 GMT",
    "display_avatar": true,
    "format": "html",
    "id": 180003547517,
    "is_blocks_post_format": false,
    "note_count": 3696,
    "post_url": "https://%blogname%.tumblr.com/post/180003547517/%slug%",
    "reblog": {
        "comment": "",
        "tree_html": "<p><a href=\"https://%reblogged-root-name%.tumblr.com/post/179851904466/%slug%\" class=\"tumblr_blog\">%reblogged-root-name%</a>:</p>\n<blockquote>\n<figure class=\"tmblr-full\" data-orig-height=\"480\" data-orig-width=\"854\" data-npf='{\"type\":\"video\",\"provider\":\"tumblr\",\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"media\":{\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"type\":\"video/mp4\",\"width\":854,\"height\":480},\"poster\":[{\"url\":\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\",\"type\":\"image/jpeg\",\"width\":854,\"height\":480}]}'><video controls=\"controls\" autoplay=\"autoplay\" muted=\"muted\" poster=\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\"><source src=\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\" type=\"video/mp4\"></source></video></figure><p class=\"npf_quote\" data-npf='{\"subtype\":\"quote\"}'>The countdown </p>\n</blockquote>"
    },
    "reblog_key": "Z6HQbA8G",
    "reblogged_from_can_message": true,
    "reblogged_from_id": "180003107724",
    "reblogged_from_name": "%reblogged-from-name%",
    "reblogged_from_title": "%reblogged-from-title%",
    "reblogged_from_url": "http://%reblogged-from-name%.tumblr.com/post/180003107724/%slug%",
    "reblogged_from_uuid": "t:1OlYisMiifKHE1rYaTbVLQ",
    "reblogged_root_can_message": false,
    "reblogged_root_id": "179851904466",
    "reblogged_root_name": "%reblogged-root-name%",
    "reblogged_root_title": "%reblogged-root-title%",
    "reblogged_root_url": "https://%reblogged-root-name%.tumblr.com/post/179851904466/%slug%",
    "reblogged_root_uuid": "t:0j94uUCnhCmEbELOsB9yEQ",
    "recommended_color": null,
    "recommended_source": null,
    "short_url": "https://tmblr.co/%short_url%",
    "slug": "%slug%",
    "state": "published",
    "summary": "The countdown",
    "tags": [
        "%tag1%",
        "%tag2%",
        "%tag3%"
    ],
    "timestamp": 1541960142,
    "title": null,
    "trail": [
        {
            "blog": {
                "active": false,
                "can_be_followed": false,
                "name": "%reblogged-root-name%",
                "share_following": false,
                "share_likes": true,
                "theme": {
                    "avatar_shape": "circle",
                    "background_color": "#280b57",
                    "body_font": "Helvetica Neue",
                    "header_bounds": 0,
                    "header_image": "https://static.tumblr.com/%header-image-name%/tumblr_static_filename.jpg",
                    "header_image_focused": "https://static.tumblr.com/%header-image-name%/tumblr_static_filename_2048_v2.jpg",
                    "header_image_scaled": "https://static.tumblr.com/%header-image-name%/tumblr_static_filename_2048_v2.jpg",
                    "header_stretch": false,
                    "link_color": "#5C3E8F",
                    "show_avatar": true,
                    "show_description": true,
                    "show_header_image": true,
                    "show_title": true,
                    "title_color": "#9f1919",
                    "title_font": "Calluna",
                    "title_font_weight": "bold"
                }
            },
            "content": "<p><figure class=\"tmblr-full\" data-npf=\"{&quot;type&quot;:&quot;video&quot;,&quot;provider&quot;:&quot;tumblr&quot;,&quot;url&quot;:&quot;https://ve.media.tumblr.com/tumblr_%video-name%.mp4&quot;,&quot;media&quot;:{&quot;url&quot;:&quot;https://ve.media.tumblr.com/tumblr_%video-name%.mp4&quot;,&quot;type&quot;:&quot;video/mp4&quot;,&quot;width&quot;:854,&quot;height&quot;:480},&quot;poster&quot;:[{&quot;url&quot;:&quot;https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg&quot;,&quot;type&quot;:&quot;image/jpeg&quot;,&quot;width&quot;:854,&quot;height&quot;:480}]}\"></figure><p class=\"npf_quote\" data-npf=\"{&quot;subtype&quot;:&quot;quote&quot;}\">The countdown </p></p>",
            "content_raw": "<p><figure class=\"tmblr-full\" data-orig-height=\"480\" data-orig-width=\"854\" data-npf='{\"type\":\"video\",\"provider\":\"tumblr\",\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"media\":{\"url\":\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\",\"type\":\"video/mp4\",\"width\":854,\"height\":480},\"poster\":[{\"url\":\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\",\"type\":\"image/jpeg\",\"width\":854,\"height\":480}]}'><video controls=\"controls\" autoplay=\"autoplay\" muted=\"muted\" poster=\"https://66.media.tumblr.com/tumblr_%video-name%_frame1.jpg\"><source src=\"https://ve.media.tumblr.com/tumblr_%video-name%.mp4\" type=\"video/mp4\"></source></video></figure><p class=\"npf_quote\" data-npf='{\"subtype\":\"quote\"}'>The countdown </p></p>",
            "is_root_item": true,
            "post": {
                "id": "179851904466"
            }
        }
    ],
    "type": "text"
}
</pre>

Hopefully the solution will be as simple and direct as it appears to have been for issue #136.

Thanks,

Muiz

**Comment by bbolli** [comment]
youtube_dl.py (with underline) is the file that is imported to download the videos. youtube-dl (with hyphen) is the name of the project and the name of its main command. `youtube_dl.py` It needs to be on Python's import path. See #150 for a solution.
