### ISSUE TITLE
Downloaded Tumblr Blog Has No Skin

### ISSUE THREAD

**Issue by humanitiesclinic** [bbolli/tumblr-utils#164]
Is the py script only supposed to download media and text? The downloaded version I have has mostly all the content, but it lacks the look and feel of the site. It's mostly static text and media. Seems like no Javascript, CSS etc.

If the py script can mirror the original look and feel, what have I done wrong?

**Comment by nightpool** [comment]
tumblr_backup does not currently backup tumblr themes, no

**Comment by humanitiesclinic** [comment]
is there any recommended software to download Tumblr themes?

**Comment by dextre** [comment]
You'd need to manually edit backup.css (or override.css) yourself to match a given theme. You might have a /theme/style.css file saved that you can copy to /override.css as a starting off point if you're familiar with CSS.

Other tools like [grab-site](https://github.com/ludios/grab-site#tumblr-blogs) will preserve the whole experience of a site, but these can be hefty backups.

**Comment by bbolli** [comment]
The API doesn't offer a way to get the theme. The script currently extracts the CSS rules from the first page of the blog and saves them under `theme/style.css`. Anything more is out of scope in my opinion. For me, it's more about the content than the presentation.
