### ISSUE TITLE
Given an error in the CLI

### ISSUE THREAD

**Issue by humanitiesclinic** [bbolli/tumblr-utils#170]
Given an error in the CLI on downloading a file eg.:
HTTP Error 403: Forbidden downloading https://vtt.tumblr.com/tumblr_o6n929k8GK1rdfg3e.mp4

How can I know what the original post id was so I can double-check how the original post looked like?

**Comment by Cebtenzzre** [comment]
Closing because this seems to be Tumblr's fault.  If you find a way to access these videos, please say so.
