### ISSUE TITLE
Embedded movies don't get downloaded even with --save-video

### ISSUE THREAD

**Issue by humanitiesclinic** [bbolli/tumblr-utils#172]
**Even with youtube_dl, and the --save-video option enabled**, I have some posts where Instagram and youtube movies are embedded in the original, but they are not downloaded. **My other videos are downloaded.** Is it possible with the current version of the script to download Instagram and Youtube, and other movies? If yes, what command line option should I use?

Btw, the error message that I get from the .py script is:
Unable to download video in post #....

**Comment by Cebtenzzre** [comment]
Please provide a few more full lines of output, if possible.  It's fine if you'd like to redact certain information, but it would help greatly if you could either provide a link to a post that has a video that does not get downloaded, or at least a section of the JSON for such a post (using the `-j` option).

**Comment by Cebtenzzre** [comment]
This should be fixed by 55b8301e212463ffb21db19532d745a4014c27fa.
