### ISSUE TITLE
module error? 

### ISSUE THREAD

**Issue by kittuar** [bbolli/tumblr-utils#174]
![image](https://user-images.githubusercontent.com/45809267/49846392-db7ee300-fd7f-11e8-9925-30e8c7e1b2bb.png)

I have no clue how to do this or what went wrong, I don't know what a Module is, nor do I understand what the httplib is. advice?

**Comment by Hrxn** [comment]
You have Python 2? It's for Python 2.x only.

**Comment by kittuar** [comment]
I just downloaded the newest version a couple days ago, where would I find that version?

**Comment by kittuar** [comment]
sorry, I'm 13 and have no idea what I'm doing

**Comment by Hrxn** [comment]
https://www.python.org/downloads/release/python-2715/

**Comment by Cebtenzzre** [comment]
@kittuar As a rule of thumb on GitHub and elsewhere, please read the README (it's called that for a reason) before opening an issue.  It states clearly that you need Python 2.7.

**Comment by kittuar** [comment]
so because I had downloaded the newest version of python, and because python 3 uses http.client instead of httplib (which took me a couple hours to figure out) I opened the file in notepad and changed the one httplib to http.client, but now it's giving me _another_ error, this one I don't know how to fix.

![image](https://user-images.githubusercontent.com/45809267/49893394-217b8b80-fe00-11e8-985f-aedd36ead9bf.png)

please advise?

**Comment by Cebtenzzre** [comment]
@kittuar Don't try to update the entire script to Python 3, it's a bigger task then you think.  Just use Python 2.  It's still being maintained and updated separately.

**Comment by kittuar** [comment]
so what should I do to do that, and/or fix the module problem above.

**Comment by dextre** [comment]
Uninstall python 3, download & install python 2.7.15 from [here](https://www.python.org/downloads/release/python-2715/), delete and redownload tumblr-utils if you've edited any files.
It won't run with python 3, they're not compatible.

https://www.youtube.com/watch?v=mwG9bzL0E_4
https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup_for_beginners.md

**Comment by kittuar** [comment]
thank you very much! fixed it and now it's running
