### ISSUE TITLE
Error: Missing blog-name

### ISSUE THREAD

**Issue by raah1** [bbolli/tumblr-utils#176]
Hi, I've followed the instructions to back up my tumblr however am unable to navigate to the backup file. When I enter the command it's coming up with the following:

Usage: tumblr_backup.py [options] blog-name ...
tumblr_backup.py: error: Missing blog-name

I see that someone else has had this issue however I'm using a Mac rather than PC and wasn't able to follow the same advice to fix it

Any help would be very much appreciated, thank you!

**Comment by Hrxn** [comment]
If your blog is, just for example, `raah1.tumblr.com`, you simply do this:
`python tumblr_backup.py raah1`

**Comment by raah1** [comment]
Thank you!!

When I included python beforehand it didn't work, but just adding the url at the end did.

I really appreciate your help, thanks so much :)
