### ISSUE TITLE
Error in downloading

### ISSUE THREAD

**Issue by TheSimpleMango** [bbolli/tumblr-utils#177]
The program stops after ~2000 posts, am I doing something wrong?
[terminal saved output.txt](https://github.com/bbolli/tumblr-utils/files/2675582/terminal.saved.output.txt)

**Comment by TiredToast** [comment]
I'm having the same issue at around 3550; I believe "TypeError: cannot concatenate 'str' and 'NoneType' objects" was the last thing that I saw before everything stalled out. I've tried it on both Windows and Mac computers, and they both stall out there

**Comment by Cebtenzzre** [comment]
Probably a duplicate of #167
