### ISSUE TITLE
Coding novice dealing with media download errors on a Mac

### ISSUE THREAD

**Issue by BryanWB88** [bbolli/tumblr-utils#181]
I am a Mac 10.14.1 user who has had no prior experience with coding, but I am desperate to archive my favorite tumblrs as comprehensively as possible before the site self-destructs on December 17.  I have been using the “python tumblr_backup.py blogname” code, and just tonight I started using “python tumblr_backup.py --save-video blogname” to download videos as well, but I’m still having a problem with downloading errors (wherein media fails to download, even though the URL still works) like the following:*
HTTP Error 403: Forbidden downloading
<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [Errno 8] nodename nor servname provided, or not known>

I have browsed the Issues section for help, but unfortunately I am simply not knowledgable enough to understand the context of the advice given in most of the relevant threads (e.g., "try option -S” in regard to the urlopen errors).

Could someone please provide me with (or direct me to) simple step-by-step instructions that even someone who knows nothing about coding can understand and follow, so that I can save these download errors in order to archive these Tumblrs as completely as possible?

Thank you very much.

*I’ve noticed that ever since I installed pip and started using --save-video, I don’t seem to get as many of these image download errors.  I am unsure as to whether I have inadvertently enabled the backup process to run more smoothly, or if these last few tumblrs I have downloaded simply have fewer problematic files.  At least one of the tumblrs I am attempting to download continues to get the aforementioned errors, however.  Ideally I’d like to be able to fix the video download errors as well, but I understand that is probably an issue I would have to take up with the youtube-dl GitHub page.

**Comment by Cebtenzzre** [comment]
Closed until a response is received; I'm assuming you've figured it out.
