### ISSUE TITLE
Backing up to external storage

### ISSUE THREAD

**Issue by BryanWB88** [bbolli/tumblr-utils#184]
I am currently out of space on my main hard drive for saving tumblr backups.  I have a network attached storage (NAS) drive to which I have been transferring as many backups as possible, but it’s a very tedious, time-consuming process, and I keep encountering errors that interrupt the transfer several hours in and force me to start over again.  Is it at all possible to run tumblr_backup.py --savevideo to download the backups directly to an external storage drive?

I am using a Mac 10.14.1.

I copied the tumblr_backup.py file (but not Python, pip, or youtube-dl) to the folder on the NAS where I would want the backups downloaded.  This is the location info shown in Get Info:
Where: Home⁩ ▸ ⁨home⁩ ▸ ⁨admin⁩ ▸ TUMBLR⁩ ▸ ⁨CODES⁩
Server: afp://ASUSTOR (AFP)._afpovertcp._tcp.local/Home/home/admin/TUMBLR/CODES/tumblr_backup.py

For comparison, this is the location info for the tumblr_backup.py file on my computer's hard drive:
Where: ‎⁨Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨*username* ▸ ⁨Documents⁩ ▸ ⁨TUMBLRARCHIVE⁩ ▸ ⁨tumblr-utils-master⁩

...and this is the cd code I have been using: cd Documents/TUMBLRARCHIVE/tumblr-utils-master

BTW, am extremely inexperienced with coding, so instructions will need to be basic and step-by-step.

Thank you for any and all help.

**Comment by bbolli** [comment]
There are two possibilities for you:
1. As you described: `cd` to the NAS folder before starting the backup. This will create the backup folder in the current directory. This is the default mode. In your case, this would mean:

        cd /Volumes/Home/home/admin/TUMBLR/CODES
        tumblr-backup.py ...

    This would create the backup inside CODES.

2. When starting the backup, you additionally pass the option `-O <folder>` or `--outdir=<folder>` to the backup command (before the blog name) and the backup will create <folder> and save all content inside it. Note that in this case, the blog name is not automatically appended, so you'd have to include it in `<folder>`, so:

        tumblr-backup.py -O /Volumes/Home/home/admin/TUMBLR/CODES/blogname ...

Where the `...` represent your other backup parameters. I'm not quite sure whether the `/Volumes/Home` part is correct, but you can check this with `ls -l /Volumes` in the Terminal app.
