### ISSUE TITLE
pyexiv2 dead link -- how to get the EXIF option?

### ISSUE THREAD

**Issue by aldunbar** [bbolli/tumblr-utils#187]
Noob here (again). The pyexiv2 link in the guide is dead. Is this necessary for tags and capturing likes? I tried --tag-index and got a blank index. What are the alternatives for getting pyexiv2?

**Comment by Cebtenzzre** [comment]
AFAIK pyexiv2 is just to add metadata to downloaded images (embedded into the image files).  You'll be fine without it.
You can still use your package manager or pip to install it.

If you're getting a blank `--tag-index`, wait for the various PRs and patches revolving around tag indexing to settle down, or try one out for yourself.  That feature doesn't work reliably yet.

**Comment by Cebtenzzre** [comment]
https://bugs.launchpad.net/pyexiv2/+bug/1743389

> pyexiv2 is now deprecated in favour of GExiv2 (https://wiki.gnome.org/Projects/gexiv2), a GObject-based wrapper around libexiv2. Thanks to GObject Introspection support, GExiv2 supports Python 2 and 3.
