### ISSUE TITLE
Not downloading all of my likes

### ISSUE THREAD

**Issue by zSwayz** [bbolli/tumblr-utils#190]
Out of the many likes that I have (5211), only 1871 likes have been downloaded. I haven't seen any errors in my terminal during the download process. Is anyone else experiencing this issue currently on the latest?

**Comment by zSwayz** [comment]
I am using the master branch.

**Comment by Code-You-Fools** [comment]
Try using #114 - just do `git clone git://github.com/aggroskater/tumblr-utils`.

**Comment by zSwayz** [comment]
I just tried that, I've managed to get about 4,900 of my likes. That's more like it! 👍
