### ISSUE TITLE
"HTTP Error 403: Forbidden downloading https://vtt.tumblr.com/[url].mp4"

### ISSUE THREAD

**Issue by mr-ptw5** [bbolli/tumblr-utils#194]
I'm getting a lot of these and missing lots of videos while trying to save my blog.

Some videos get saved, but hardly many of them.  I feel like more than 75% of my videos from my blog are not being downloaded.

I am using a cookies.txt file from a logged-in tumblr session.

Can anybody give any tips?  Sorry

**Comment by kylewjackson** [comment]
This was happening to me earlier, but when I checked the source of some of the videos tumblr, they were unavailable. I'm not sure if it's happening on videos that are still live for you, but it could just be that they've been deleted on the blog itself.

**Comment by Hrxn** [comment]
Yes, this is expected. Check some of these in your browser and report the URL here if you actually manage to find one that is actually still working.

**Comment by mr-ptw5** [comment]
I'll check them when I get home in the next hour!  Many of the ones that didnt get downloaded are playable when I view them on my blog, but I have not checked whether they are playable when viewed from their original blogger (none of them are my original posts)

**Comment by mr-ptw5** [comment]
You guys are right!  I was expecting to see more videos because I'm not used to the UI of the extraction--but everything that should be there seems to be there!  Sorry for the trouble.
