### ISSUE TITLE
Long length tags bug out --tag-index

### ISSUE THREAD

**Issue by XenobioBat** [bbolli/tumblr-utils#198]
As it reads on the tin. 
I believe the problem right now is an issue of trying to save a --tag-index of a blog where someone uses an excessively long tag as you might see here.
![image](https://user-images.githubusercontent.com/40021571/50199361-417de400-0305-11e9-81c9-bead7b8ed194.png)

This is just a theory, but I have noticed it as a recurrent thing.

EDIT: Forgot to say that this is only an issue when I use --tag-index on a few blogs so far. These blogs archive just fine without it.

**Comment by Cebtenzzre** [comment]
I think this could be included into #140.  It's part of the same idea that we shouldn't use tags as folder names directly.

**Comment by LoverIan** [comment]
Oh very much a shame. Feel free to merge it with #140  or however that works, I wish ya'll the best of luck and look forward to the solution.

**Comment by bbolli** [comment]
Fixed by #140
