### ISSUE TITLE
KeyError: 'title'

### ISSUE THREAD

**Issue by bastispangler** [bbolli/tumblr-utils#203]
I tried to backup one of my blogs. It worked 5 minutes ago with another one, but the last one won't run.

I ran the commant:
python tumblr_backup myname.tumblr.com
as always. I even downloaded the "latest" Version of the script.

I get:

Getting basic information.

Traceback (most recent call last):
  File "tumblr_backup.py", line 345, in <module>
    backup(account, use_csv, save_folder, start_post)
  File "tumblr_backup.py", line 286, in backup
    title = tumblelog["title"]
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: 'title'

Anyone an idea what's up here?

**Comment by Cebtenzzre** [comment]
Wait, what?  Why is BeautifulSoup4 in the stack trace?
What version/branch of tumblr-utils are you using?  The line numbers don't match up with the latest git master.

**Comment by bastispangler** [comment]
LOL I just realized I was using this all the time: https://github.com/bdoms/tumblr_backup instead of yours… thanks! Sorry for stealing your time mate!
