### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by indrakaw** [bbolli/tumblr-utils#204]
By default errors show on screen. It's possible to redirect output to a file, but it isn't effective. My suggestion is an option to enable progress logging on a file in output directory, eg `errors.log` or just `logs.txt`.

**Comment by Cebtenzzre** [comment]
Looking back at this, I bet the cause of your issue is that this script writes to both stdout and stderr. To get both status messages and errors, do
```
python tumblr_backup.py [...other arguments...] >log.txt 2>&1
```
Note the `2>&1` at the end. That should work on all operating systems.
