### ISSUE TITLE
Unauthorized Getting API

### ISSUE THREAD

**Issue by sherbertsherbert** [bbolli/tumblr-utils#211]
Hi, I'm running into this issue

HTTP Error 401: Unauthorized getting https://api.tumblr.com/v2/blog/[BLOG]/posts?reblog_info=true&api_key=&limit=1

When trying to download my cmd is as follows: tumblr_backup.py -D -r -R [blog]. I thought it was an issue with the blog, but I have retried various others and it gave me the same error. I had used an older version of tumblr downloader (prior to 26/6/2020) and then downloaded and updated to the recent one - which the API had been removed. But I still faced the same error. 

Is there a way to authorize the API or is this a website issue? Sorry and thank you.

**Comment by HazelDomain** [comment]
Hello- [this was answered in a different thread](https://github.com/bbolli/tumblr-utils/issues/210) but I'm pasting slowcar's answer from there, here, in case anyone finds this thread first:

To get an API key log in to Tumblr and go to https://www.tumblr.com/oauth/apps
Enter stuff into the fields marked with an asterisk. We just wrote "backup tumblr posts" into the description.
The whole process is automated, afaik there is no human interaction whatsoever, but as it is connected to your account you should probably stay civil.
Click two buttons, you get your API_KEY.
Open the backup.py from these tools, look for API_KEY and replace the existing with your new one.

**Comment by sherbertsherbert** [comment]
Thank you HazelDomain! It works now.
