### ISSUE TITLE
HTTP Error 401: Unauthorized when trying to backup blog

### ISSUE THREAD

**Issue by overdue82** [bbolli/tumblr-utils#212]
I never used to have problems backing up my blog or any blog. But today I go to back up my blog and now I'm getting these errors. I can't back up any blog through this app anymore. This was the only app that actually made a real blog backup unlike other apps and tumblr's backup which just ripped the image files. Is this fixable or has tumblr completely ruined this app as well?

HTTP Error 401: Unauthorized getting https://api.tumblr.com/v2/blog/blktangledhe
art.tumblr.com/posts?reblog_info=true&api_key=

**Comment by bbolli** [comment]
You need to get your own API key from Tumblr. See https://github.com/bbolli/tumblr-utils/issues/210#issuecomment-649788008
