### ISSUE TITLE
Failed back up of a blog

### ISSUE THREAD

**Issue by Dragonfly8790** [bbolli/tumblr-utils#220]
I cannot back up a blog. I have done it succesfully several times in the past, so I suspect it has something to do with the latest change to tumblr's own code. 
I re-downloaded tumblr-utils today, thinking my version might be outdated, but the issue remains. 
I use the command "tumblr_backup.py <blog name>" and I get several lines of 
"HTTP Error 401: Unauthorized getting https://api.tumblr.com/v2/blog/<blog name>/posts?reblog_info=true&api_key=&limit=1". 
The blog is not password protected, but it is a side blog. However, I checked it on some other tumblrs too, and it gives the same error.

**Comment by Cebtenzzre** [comment]
Please read the comment in the script here:
https://github.com/bbolli/tumblr-utils/blob/01d352801a476c6e7d9e89d804f46cc5e963db75/tumblr_backup.py#L104-L105
This changed in June when Tumblr disabled the public API key (see [this comment](https://github.com/bbolli/tumblr-utils/issues/210#issuecomment-649826874) from a Tumblr engineer).

@bbolli We should probably document this better. At least in tumblr_backup.md but preferably in the README. I would make a PR for this but mine never get merged :(

**Comment by Dragonfly8790** [comment]
Thank you so much! I didn't check the script, and I couldn't find anything in readme file. I forgot that change was so long ago, I should've checked older issues.
