### ISSUE TITLE
APi key

### ISSUE THREAD

**Issue by Letstrytumblr** [bbolli/tumblr-utils#224]
Hi,
I'm really sorry to bother you, I've been looking for a way to back up tumblr on mac and there isn't any. So.
I've already successfull used this tumblr backup for windows and it was wonderful, but now on mac I'm stuck on the Api Key. I've tried to ask for it on tumblr, but they want a url and an url default callback and I don't know what to use. I've tried "github.com" but it doesn't work. Do I have to use https://github.com/bbolli ? Or a real working app? Obviously I don't have any app to register with, I'm just learning to code and I just want to back up some blogs.
Sorry if this is a stupid question.
Thank you for your time.
LTT

**Comment by bbolli** [comment]
> Get your personal Tumblr API key at https://www.tumblr.com/oauth/apps. Follow the instructions there; most values entered don't matter. The API key must then be copied between the single quotes in the source code at around line 105 (the line starts with `API_KEY =` ).
