### ISSUE TITLE
AttributeError: 'URLError' object has no attribute 'code'

### ISSUE THREAD

**Issue by khaygiel** [bbolli/tumblr-utils#230]
I'm using commit be22b8c of tumblr-utils. I haven't really used a program like this before. The command I typed to start the program was this:

C:\Users\Username\Downloads\bbolli-tumblr-utils-be22b8c\bbolli-tumblr-utils-be22b
8c>tumblr_backup.py [tumblrusername]

It got to 1,101 posts before showing me this and then stopping:

Traceback (most recent call last):
  File "C:\Users\[Username]\Downloads\bbolli-tumblr-utils-be22b8c\bbolli-tumblr-uti
ls-be22b8c\tumblr_backup.py", line 1236, in <module>
    tb.backup(account)
  File "C:\Users\[Username]\Downloads\bbolli-tumblr-utils-be22b8c\bbolli-tumblr-uti
ls-be22b8c\tumblr_backup.py", line 597, in backup
    soup = apiparse(base, MAX_POSTS, i)
  File "C:\Users\[Username]\Downloads\bbolli-tumblr-utils-be22b8c\bbolli-tumblr-uti
ls-be22b8c\tumblr_backup.py", line 208, in apiparse
    if e.code == 429:
AttributeError: 'URLError' object has no attribute 'code'

Thank you!

**Comment by Cebtenzzre** [comment]
@khaygiel Looks like the most recent commit introduced a regression. You could try [the previous commit](https://github.com/bbolli/tumblr-utils/tree/d0158de44ddbb8d440c7b2427392a642fd37f26f), or [my fork](https://github.com/cebtenzzre/tumblr-utils) (which provides a `--resume` option that would avoid downloading those 1k posts again).

https://github.com/bbolli/tumblr-utils/blob/be22b8cfa60d547868694d6c8ce80265009fb896/tumblr_backup.py#L207-L208
@bbolli urllib2.URLError is a subclass of EnvironmentError but has no `code` attribute. This if statement should check `isinstance(e, HTTPError)` before it tries to read `e.code`.
