### ISSUE TITLE
Python File Opens But Nothing Happens ??

### ISSUE THREAD

**Issue by sublucat** [bbolli/tumblr-utils#231]
Hello, I actually used this program in the past and it worked perfectly, but now it doesn't work for some reason....??
As shown on the picture I attached, when I type in the command and hit enter, the [tumblr_backup.py] file opens but nothing happens. I'm really confused on what I'm doing wrong since the only thing I changed in my python file is adding my tumblr api code.

- The version tumblr-utils: caa912f (downloaded today [July 27th, 2021])
- No crashes or a backtrace
- The exact command I ran: 
![Issue](https://user-images.githubusercontent.com/87994366/127025685-ce6ea15f-156a-43d5-97e3-ce6b71ab18eb.PNG)

**Comment by Cebtenzzre** [comment]
That seems like what would happen if you have no file association for python scripts. Try running it as `python tumblr_backup.py sublucat` instead (assuming you have Python 2 installed and it is on your PATH).

**Comment by sublucat** [comment]
I really appreciate the fast response. I tried python tumblr_backup.py sublucat as you said, but it still didn't do anything. 
So I checked the PATH as you mentioned in case I missed something but I can't seem to figure out the issue.

The top image is the command line and the bottom images is the PATH with Python27 in it.

![Issue_2](https://user-images.githubusercontent.com/87994366/127029194-0d0adbc9-84c8-4a65-9de9-fb04c9c55943.PNG)

![Issue_2b](https://user-images.githubusercontent.com/87994366/127029204-bc85097f-ef2a-4540-a6ca-6cfa6dc0cdd2.PNG)

**Comment by bbolli** [comment]
Is python.exe in the folder C:\Python27?

Can you try giving the complete path to python, e.g. `C:\Python27\python.exe tumblr_backup.py sublucat`? Is

**Comment by sublucat** [comment]
Yes, python.exe is in the C:/Python27 folder.
I tried the path you suggested, and now it's giving me this error message.

![Issue_3](https://user-images.githubusercontent.com/87994366/127034582-540978bc-93f9-4c4b-a58b-7943df816cc6.PNG)

**Comment by Cebtenzzre** [comment]
@sublucat 401 unauthorized most likely means your API key is wrong. Make sure you've copied your OAuth consumer key.

**Comment by sublucat** [comment]
@Cebtenzzre Thank you for the input! After changing the OAuth consumer key it started exporting the posts! 
Although there are some codes that says error should I be looking into the folder again to make sure?

![Issue Solved I guess](https://user-images.githubusercontent.com/87994366/127039189-5fc7dd4b-8f12-4e2e-a233-6c33ba849a70.PNG)

**Comment by Cebtenzzre** [comment]
@sublucat That's because of non-ASCII characters in posts. It happens easily on Python 2 because raw bytes are interchangeable with ASCII strings. Feel free to open a separate issue mentioning that UnicodeDecodeError. For a quick fix, unicode works better on [my fork](https://github.com/cebtenzzre/tumblr-utils), especially when used with Python 3.

**Comment by sublucat** [comment]
Alright! Thank you so much for helping!! :)
