### ISSUE TITLE
Help with API code

### ISSUE THREAD

**Issue by somnomania** [bbolli/tumblr-utils#233]
I'm an imbecile, and an extreme novice at code and the command line. I'm trying to get my Tumblrs downloaded before the very recent tag bans start wiping things out, and I'm stuck on the API step. I have a code now, but I don't understand what to do with it, and also it seems from the OAuth page like it will limit me to 5000 downloads a day?

**Comment by Cebtenzzre** [comment]
To set up your API key, put the OAuth Consumer Key inside the quotes on line 105 of `tumblr_backup.py`. It should look like `API_KEY = 'MY_CONSUMER_KEY'`. This is explained in tumblr_backup.md [here](https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup.md#1-installation).
