### ISSUE TITLE
Issue with cookie.txt and ydl_options

### ISSUE THREAD

**Issue by irregularhound** [bbolli/tumblr-utils#237]
Hello,

As of this date and my first backup, I used this hash: https://github.com/bbolli/tumblr-utils/commit/892e28d73b75d57c58b24aec00ea4190f17b61c3

When I first used tumblr-utils on 2/23/24 according to the instructions laid out [here](https://docs.google.com/document/d/1yBWlk-yEgpSoEh3c9oLhz_kbLtUGqbqzOpCtJsvQgjI/edit), it worked just fine - minus the inability to download some videos. The document linked provides a solution to this, which is to add a line to read Tumblr cookies in tumblr_backup.py. When I added this and started the backup process, a lot of errors come up. Too many of them at once for me to properly document it. However, I notice a certain line kept showing up:

_AttributeError: 'HTTPResponse' object has no attribute 'get_content_length'_

I have tried a variety of things to fix this, including removing the line entirely from the tumblr_backup.py file and using the --cookiefile command to point to the file. This does nothing either.

Not sure what to do. Any advice would be greatly appreciated!

**Comment by cebtenzzre** [comment]
You were already using my fork if you saw that error, that's https://github.com/cebtenzzre/tumblr-utils/issues/15.
