### ISSUE TITLE
Tumblr Backup: Dashes in tags

### ISSUE THREAD

**Issue by ohhdemgirls** [bbolli/tumblr-utils#44]
Doing `python tumblr_backup.py -t muh-face ixnay-on-the-oddk`

Doesn't get images/posts tagged `muh-face` I guess it's because of the included dash?

NSFW: http://ixnay-on-the-oddk.tumblr.com/tagged/muh-face

**Comment by AGSPhoenix** [comment]
@WyohKnott, did you ever find any more information about this? This bug is still present in the current release.

**Comment by WyohKnott** [comment]
@AGSPhoenix No sorry, I don't recall anything about it.

**Comment by andrewia** [comment]
I did some testing (you can try it out yourself with my test blog at http://pyapitest.tumblr.com) and it seems that the Tumblr API considers dashes and spaces to be different while the website consider dashes to also be spaces.  Interestingly, spaces do not also count as dashes on the website.  

Also, if anyone has issues grabbing posts by using tags with spaces in them, surround each tag with quotation marks.

**Comment by bbolli** [comment]
> Also, if anyone has issues grabbing posts by using tags with spaces in them, surround each tag with quotation marks.

This is always needed in a standard shell, and not specific to this command. These are the possibilities:

    python tumblr_backup.py -t "muh face" ixnay-on-the-oddk
    python tumblr_backup.py -t 'muh face' ixnay-on-the-oddk
    python tumblr_backup.py -t muh\ face ixnay-on-the-oddk

The backslash in the last example prevents the space from separating the two words ``muh`` and ``face``, so ``muh face`` is passed as one single argument to tumbr_backup.

``man bash`` has all the rules. Search for ``QUOTING``.
