### ISSUE TITLE
Tumblr Backup: Source dumped to screen

### ISSUE THREAD

**Issue by ohhdemgirls** [bbolli/tumblr-utils#51]
Running `python get.py -x -t me eggkid` is get https://i.imgur.com/pCDUuJy.png

Seems to complete okay, just not seen it do this before.

**Comment by bbolli** [comment]
What is the content of `get.py`? It's not part of this repo.
Normally, tumblr_backup.py dumps the content of posts that have an unknown post type.

**Comment by bbolli** [comment]
OK, the start of the message is

    SAXParseException: <unknown>:2:1735: not well-formed (invalid token)

The character at line 2, character 1735 is 037 (octal), as part of this tag, in the first character of attribute `caption`:

    $ grep MUJI xx.txt | od -c -t x1
    0000000   <   p   h   o   t   o       o   f   f   s   e   t   =   "   o
             3c  70  68  6f  74  6f  20  6f  66  66  73  65  74  3d  22  6f
    0000020   2   "       c   a   p   t   i   o   n   =   " 037 346 234 250
             32  22  20  63  61  70  74  69  6f  6e  3d  22  1f  e6  9c  a8
    0000040 343 201 256 345 256 266       /   /       M   U   J   I   "
             e3  81  ae  e5  ae  b6  20  2f  2f  20  4d  55  4a  49  22  20
    0000060   w   i   d   t   h   =   "   8   4   5   "       h   e   i   g
             77  69  64  74  68  3d  22  38  34  35  22  20  68  65  69  67
    0000100   h   t   =   "   5   6   4   "   >
             68  74  3d  22  35  36  34  22  3e

This character is not allowed by the XML specification.
