### ISSUE TITLE
Rip videos, fetch new posts only by default, filter reblogs option

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#54]
- At least download the video file into /videos. Save extension as mp4 or mov, what the extension is is near where the video data link is in the code for video posts.

- Only new content from previous rips should be fetched.

- Filter reblogs or allow a flag to pull posts from that speciic blog only

**Comment by bbolli** [comment]
Sorry, this is too unclear. Please provide examples with the current result and what you'd like to have as a result. And make an issue per issue :)
