### ISSUE TITLE
Blog archives missing video data locally (NSFW links in issue)

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#55]
./tumblr_backup.py -I o -t me,Me,ME -O naked-yogi naked-yogi

This will grab all the selected posts, it will grab posts where there was a video but not the tumblr-posted (or any, really) video file making it an incomplete archive.

It misses the video in this: http://naked-yogi.tumblr.com/post/120266402218/naked-yogi-1-2-3-4-hearts-lost

I don't know how you want me to demonstrate that the script doesn't pull the video, but, it doesn't. 

A possible solution:

Detect youtube-dl installation, if found use that to do the backend work of doing the video ripping saving them to .../$blog-name/videos, and if not found print to STDOUT or log at least, the URL(s) of pages with a tumblr-sourced video so that we can go back later.

This way all you would have to do is have youtube-dl do the work of downloading the video, save it to .../$blog-name/videos and then simply re-link the videos source in the file to .../$blog-name/videos/file.mp4 in the particular post.

So the command to get that video file would be:

youtube-dl http://naked-yogi.tumblr.com/post/120266402218/naked-yogi-1-2-3-4-hearts-lost

all that needs to happen is for tumblr_backup.py to recognize when theres a video post on that blog, and act accordingly using some of the suggestions above.

**Comment by bbolli** [comment]
Use the api-v2 branch with option `--save-video`.

**Comment by WyohKnott** [comment]
Tumblr now blocks the d/l of audios and videos (probably by checking referrer).
