### ISSUE TITLE
Only new content from previous blog rips should be fetched (git-like) on subsiquent runs.

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#56]
Example, I run this today for the first time:

./tumblr_backup.py -O justgirlythings justgirlythings

In 5 days, I run it again, and it gets *all* posts again, instead of journaling in /justgirlythings/progress.json (or something like that) when the last time I ran the command so by default it will skip older posts and focus only on whats been missed. This saves on archiving time and traffic generated.

This would be a very handy feature, if  you don't find it ideal to make this the default action then something like -n for new posts only (assuming the commands been run before) would suffice. Think of it like resuming a paused download, or more accurately git where only new changes are fetched.

**Comment by bbolli** [comment]
Use option `-i`. The help calls this "incremental mode".
