### ISSUE TITLE
Filtering out reblogs in a target blog from being archived

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#57]
Sometimes I only want what the target blog posted, not what they share from others. This would make a dandy flag in the backup script.

**Comment by bbolli** [comment]
Use the version in the api-v2 branch with option `--no-reblogs`. The v1 API does not indicate whether a post is a reblog or not.

**Comment by vxbinaca** [comment]
Thanks for pointing all this out, apologies for wasting your time with useless issues.

**Comment by bbolli** [comment]
No problem; maybe I should add a hint to the other branch in the master README :-)

**Comment by vxbinaca** [comment]
Yes please edit the readme with the exact commands I need to enter because I'm having difficulty replicating the branch switch on my workstation at home. I switch branches and it doesn't pull the 41 waiting changes. I got it working on my laptop at work but not at home.

**Comment by vxbinaca** [comment]
python tumblr_backup.py --save-video -I o --no-reblogs  -O naked-yogi naked-yogi
Usage: tumblr_backup.py [options] blog-name ...

tumblr_backup.py: error: no such option: --no-reblogs



I've deleted the script, and re-cloned 5 times.  You merged api-v2 into master. I'm on master. I don't understand whats going on. The script actually doesn't contain the word "reblogs".

**Comment by vxbinaca** [comment]
Mispelled flag in your first reply. I unpluralised and it's running.

Okay, now onto timeouts.

**Comment by bbolli** [comment]
You just cloned while I was doing the branch switch. I'm done now. Please pull again. The option is called `--no-reblog` without the 's'.

**Comment by bbolli** [comment]
Ooops, sorry about the misspelling.

**Comment by bbolli** [comment]
I'll fix it for other readers.

**Comment by Bl4Cc4t** [comment]
Apparently, every blog I backup with the flag `--no-reblog` doesn’t do anything. The reblogs are saved even with the flag activated (and this is a lot of data for some blogs).
Sorry that I have to reinvoke this issue though

**Comment by bbolli** [comment]
This works here on my test blog bbtests.tumblr.com. What blog are you trying to backup?
