### ISSUE TITLE
missing URLs that really are there (mixed work or 404) in api-v2 (NSFW links)

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#58]
$ ./tumblr_backup.py --no-reblog --save-video -t me,Me,ME,lover,yoga -O naked-yogi naked-yogi
timed out downloading http://41.media.tumblr.com/0ffc03585544d18d5751844373432b45/tumblr_nmbeb2BSx71rtx758o1_1280.png
HTTP Error 404: Not Found downloading http://36.media.tumblr.com/0c9d90742511815f976302118c5f93ca/tumblr_nj00ioLzQj1rtx758o1_1280.jpg
HTTP Error 404: Not Found downloading http://41.media.tumblr.com/905fa8a8bddbbba619fa3da5842c8bb7/tumblr_nj00ioLzQj1rtx758o3_1280.jpg
HTTP Error 404: Not Found downloading http://40.media.tumblr.com/b20e284dbe7501d6a832fc9262280518/tumblr_nj00ioLzQj1rtx758o2_1280.jpg
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://naked-yogi.tumblr.com
timed out downloading http://41.media.tumblr.com/c175f6bf8ea4d764af8852d8ad5246de/tumblr_njzb7uMYSZ1rtx758o1_1280.png
timed out downloading http://41.media.tumblr.com/822ef3ef4af1932a16bd8637c2955e49/tumblr_niebc3JTRt1rtx758o3_1280.jpg
timed out downloading http://33.media.tumblr.com/65d9403a341397690949d2c8932cbefd/tumblr_nfeclxtbza1rtx758o1_400.gif
timed out downloading http://41.media.tumblr.com/0ae2428b589eef62cac11fb25ea94478/tumblr_nbjbv16TQJ1rtx758o2_1280.jpg
timed out downloading http://41.media.tumblr.com/6768b1ea30bc2bac7b4709053ef206a1/tumblr_n8mdbvqSMS1rtx758o1_1280.jpg
timed out downloading http://33.media.tumblr.com/051100bfa77c74f5be1bcf62dcd70b0d/tumblr_mxox9rsYgR1ry21ujo1_250.gif
timed out downloading http://41.media.tumblr.com/f235d092f2d082d17674edabf28be096/tumblr_mptu6wbad71r60rf6o1_500.jpg
naked-yogi: 488 posts backed up

Am I being throttled? Because, 

http://41.media.tumblr.com/0ffc03585544d18d5751844373432b45/tumblr_nmbeb2BSx71rtx758o1_1280.png

Works, some of the others do too, but most don't.

**Comment by bbolli** [comment]
Could you try to increase the value of HTTP_TIMEOUT around line 90 and check if this improves things?

**Comment by vxbinaca** [comment]
Preliminary results: Okay so I have a batch file that pulls a BUNCH of tumblrs, and it's running smooth so far. I was getting some 404s on new post page requests (the stream updates of new posts, not the posts themselves). I set it from 30 to 60. If  all goes well, I will create a pull request with it set to 90 just to be safe.

It's still running right now though, and I have like a good 9 gigs to go.

**Comment by WyohKnott** [comment]
Server 40 and 41 are often down for some reason. It happens not only with tumblr-backup but with other services like Feedly too. Maybe you could write your script in such a way that it delays the update when too much error are detected.

**Comment by vxbinaca** [comment]
@WyohKnott so I neded up committing a 90 second timeout and I get better results now but on that blog theres a few legitimate 404s. @bbolli I'm calling this one solved and moving onto new problems later once I can document them thoroughly.
