### ISSUE TITLE
Blog names with dashses in them causing seizures in tumblr_backup.py also possible DNS problems

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#63]
```<urlopen error [Errno -2] Name or service not known> getting http://api.tumblr.com/v2/blog/p-e-n-e-l-o-p-e-m-a-c-h-i-n-e.tumblr.com/posts?api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1&offset=8````

*snip*

```HTTP Error 408: Request Time-out getting http://api.tumblr.com/v2/blog/p-e-n-e-l-o-p-e-m-a-c-h-i-n-e.tumblr.com/posts?api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1&offset=8```

*snip*

```p-e-n-e-l-o-p-e-m-a-c-h-i-n-e: Getting posts 8 to 8 of 9 ```

I'm seeing name resolution errors. I run NSCD and use OpenDNS on my router for resolution.

**Comment by vxbinaca** [comment]
Semi-related to your script:

I found multiple problems in youtube-dl for vid.me and other video hosts that were halting my large blog rips. Bus reporting one script leads to bug reports for others.


Tentatively hold off on closing this as it may be VPN related, the timeouts at least. Give me another 24 hours until I can test this again better.

**Comment by bbolli** [comment]
@vxbinaca , any progress with this issue?
You could also try to use Google's DNS servers if you suspect DNS failures from OpenDNS: 8.8.8.8 and 8.8.4.4.

**Comment by vxbinaca** [comment]
@bbolli I use OpenDNS or iPredators DNS and since I run Linux, I use NSCD to cut down on lookups so it caches the results.

The problem was vid.me, if I recall, wasn't being handled right in embeds. Feel free to close for now. Also the vast vast majority of my problems with youtube-dl and tumblr-utils are related to the 404s on embeds, videos being pulled and such.

Feel free to close for now.

**Comment by vxbinaca** [comment]
I'm not getting this problem any more on the two blogs I tested with dashes in them, feel free to close.

**Comment by bbolli** [comment]
Ok, closing per your request.
