### ISSUE TITLE
Re-check Downloaded Post

### ISSUE THREAD

**Issue by tetrahydra** [bbolli/tumblr-utils#65]
Hello,

Sometimes, the downloading process got time out and 403.

May I suggest that you include an option to recheck and compare local contents to the ones in the server. Only if locally not exist, then download.

Or perhaps, the option already exist. If so, how do I achieve this?

Thank you.

**Comment by bbolli** [comment]
It's simpler to do a complete backup in this case. For an imcremental backup, use option `-i`.
