### ISSUE TITLE
Failing to grab some urls due to post name in url

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#66]
```
$ ./tumblr_backup.py --no-reblog --save-video -I o -t me,mine -O kiefeon kiefeon

WARNING: Falling back on generic information extractor.           
ERROR: Unsupported URL: http://kiefeon.tumblr.com/post/98249346023/mine#_=_
Unable to download video in post #98249346023                                                  
kiefeon: 1414 posts backed up
```

Why not just use regex to drop everything after the postID to avoid errors like this?

**Comment by bbolli** [comment]
You'd have to take this issue to the youtube-dl maintainer here: https://github.com/rg3/youtube-dl
tumblr-utils just embeds youtube-dl.

**Comment by vxbinaca** [comment]
Ah, sorry. Didn't know if it was an issue with youtube-dl or tumblr-utils. I'll file a bug report.
