### ISSUE TITLE
ctrl+c won't stop tumblr_backup.py

### ISSUE THREAD

**Issue by sqbing** [bbolli/tumblr-utils#68]
```
timed out downloading http://vt.tumblr.com/tumblr_nv4e3libSY1udqctx.mp4
timed out downloading http://41.media.tumblr.com/8b65e6a2c6b13f30d79b53e1e3e9d2ab/tumblr_nu3k5p7yai1udqctxo3_1280.jpg
^C^C^C^C^C^C^C^C

stopping threads.....
```

**Comment by bbolli** [comment]
Well, it does if it not waiting for the network :-)

This is a problem inherent in any Python program that does network I/O. The interrupt is detected only when Python code runs, but the program is waiting for a network packet in the socket library, which is written in C. So the threads can only be stopped once the socket library returns the timeout error to the Python code.

**Comment by sqbing** [comment]
Can you add support for double ctrl+c to force terminate download threads instead of endless waiting.

**Comment by bbolli** [comment]
No, I can't. It does not depend whether you press ^C once or twice; the Python code does still not receive the KeyboardInterrupt exception as long as it's waiting in the socket library.

You can do something like `kill $(pidof tumblr-backup)` from a different terminal window.

**Comment by sqbing** [comment]
@bbolli thanks
