### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by Hrxn** [bbolli/tumblr-utils#69]
Hey, just tried to run `tumblr_backup.py` on my Windows system (Windows 10 x64 15.11), but it does not work:

```
C:\Pthx>Python tumblr_backup.py
Traceback (most recent call last):
  File "tumblr_backup.py", line 11, in <module>
    from httplib import HTTPException
ImportError: No module named 'httplib'

C:\Pthx>
```

I have Python 3.5.0. Is it even compatible with Python 3? The Readme indicates nothing here..

**Comment by bbolli** [comment]
These tools only run with Python 2. Sorry for not making this clear in the README. I'll amend it.

**Comment by Hrxn** [comment]
Thanks for the clarification!

I downloaded and extracted the Python 2.7.11 MSI package, can confirm that it works with tumblr-utils running on Windows 10.

I also tried the `2to3.py` bundled with the Python installer for automatic translation to Python 3, this correctly transforms all the imports, for example, but it doesn't work with the whole script.

**Comment by wolfxxi** [comment]
I've installed Python 2.7.11 MSI package and on Windows 10 I am still getting the exact message above:

C:\Users\Matt\Desktop\tumblr-utils-master\tumblr-utils-master>tumblr_backup.py -l bindingbynature
Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\tumblr-utils-master\tumblr-utils-master\tumblr_backup.py", line 11, in <module>
    from httplib import HTTPException
ImportError: No module named 'httplib'

**Comment by Hrxn** [comment]
You probably still have Python 3 installed as well and this gets used instead..

You can try to run `python2 tumblr_backup.py ......`, or if that doesn't work, use the full path to the Python binary, e.g.
`C:\Users\Matt\Desktop\tumblr-utils-master\tumblr-utils-master>C:\Python27\python.exe tumblr_backup.py ....`

**Comment by wolfxxi** [comment]
Thanks, I'm just uninstalling other versions of Python and then trying again.
