### ISSUE TITLE
--save-video fails without notice

### ISSUE THREAD

**Issue by Hrxn** [bbolli/tumblr-utils#70]
(I guess this applies to `--save-audio` as well, but I did not test.)

My setup: `Windows 10 Pro x64, Python 2.7.11`

So far tumblr-utils works really fine, I'm impressed. My hat's off to you!

There is only this small exception, and this concerns an optional dependency.

From tumblr_backup.md
> There are two optional dependencies that enable additional features:
To backup audio and video, install youtube-dl.
To enable EXIF tagging, install pyexiv2.
The fastest option to install these packages is via the package manager of your operating system (apt-get, synaptic, yum, brew, etc). If this is not feasible, download and install from the links above.

As a Windows user, I just have a `youtube-dl.exe`, although it is in my `PATH`. Obviously, it can't work this way.

I skimmed `tumblr_backup.py` trying to find out how `youtube-dl` is called, but I guess it already fails here at [Line 36](https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup.py#L36), without returning an error message unfortunately.

Is there an easy way to make this import work, like using the `youtube-dl` version from their site, this one: `curl https://yt-dl.org/downloads/2016.01.23/youtube-dl`

This is not text/py, but I can use it with the Python interpreter on Windows, apparently.
So what should I do to make the import work? Can I just place `youtube-dl` somewhere specific?

**Comment by bbolli** [comment]
Thanks!

The correct way to install Youtube-DL so that other Python programs can import it is to download the `.tar.gz` archive, then use 7-Zip (or some other unzipper that can handle `.tar.gz` files) to extract the inner `youtube_dl` folder (the one that's currently about 3MB in size) to your Python's site-packages folder, e.g. `C:\Python27\Lib\site-packages`. There, it will automtically be found by tumblr_backup.

If you did it right, there will be the file `...\Python27\Lib\site-packages\youtube_dl\__init__.py` (plus many others, of course), and this should just work in your Python shell:

```
>>> import youtube_dl
>>> youtube_dl.YoutubeDL
<class 'youtube_dl.YoutubeDL.YoutubeDL'>
>>>
```

**Comment by Hrxn** [comment]
Hey, sorry for my late reply, but I was barely at home the last days.

I extracted the content of the `youtube_dl` directory from the archive file into `..\Lib\site-packages`, overwriting some `Readme` file that was already present there (they should use sub-directories), and tried in the Python shell:
``` 
>>> import youtube_dl
>>> youtube_dl.YoutubeDL
```
And this did work! Tried to download some videos from some random blog, worked as well. Thank you!

You don't see any status or progress information written to the CLI while executing `tumblr_backup.py`, i.e. youtube-dl is silently running in the background, but I guess this is intentional, right?

**Comment by WyohKnott** [comment]
May I recommend instead to install it with:

```pip install youtube-dl```

in a command line. It's easier for newcomers I believe.
Maybe you can add this line in the readme?

**Comment by bbolli** [comment]
> pip install youtube-dl

Does this work in Windows?

**Comment by WyohKnott** [comment]
Yes, with Python in the PATH, as it should be.

**Comment by Hrxn** [comment]
Yes, you can use `pip` on Windows..
The thing is, I already had Python 3.5.0 installed and I didn't need more mess in my PATH. I guess you can repair your path settings manually and use both versions simultaneously, but why bother?

Python 2.x for Windows is only distributed as MSI installer packages (Which is actually the right way for Windows), but you can unpack them to a specific directory and use the `python.exe` there. That is how I do it. And personally I don't mind installing youtube-dl in this "manual" way, as long as there are no functional differences, I'm happy..
