### ISSUE TITLE
have youtube-dl call --download-archive

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#71]
The reason why this is smart and because every time you pull a blog, it gets the video too. Using that flag allows you to skip already downloaded video. You could set the archive list to somewhere say, in the CWD of the script or in ~/.tumblr-dl-youtube-dl-archive or something

**Comment by bbolli** [comment]
Yeah, I realized this now. I'll have to patch youtube-dl first, because it's impossible to get the name of the downloaded file out of it without effectively downloading the file.

**Comment by vxbinaca** [comment]
Why patch it? Why even include the binary? You should just have to replace all mentions of the command with ones that have the added flag. Except that only instances run within your script should be using a seperate archive file located in the CWD of the git folder.

Speaking of fixes, why not implement a flag for calling native binaries? ```--call-native-bins``` would be my suggestion. I keep hyper-fresh pulls of youtube-dl.

**Comment by Hrxn** [comment]
> The reason why this is smart and because every time you pull a blog, it gets the video too.

With or without `-i, --incremental     incremental backup mode`?

**Comment by bbolli** [comment]
If you want to backup only new posts, use option `-i`.
