### ISSUE TITLE
Authentication needed

### ISSUE THREAD

**Issue by vxbinaca** [bbolli/tumblr-utils#73]
A few blogs I archive need authentication to view them. Ex: naked-yogi.tumblr.com

**Comment by WyohKnott** [comment]
When a user choose to disable "Allow logged-out users to see this blog" in their blog settings, it's not possible to view them through the API.

(Well it is somehow but it would break the Terms of Use of the Tumblr API, and I've already lost my account once because of that).

**Comment by bbolli** [comment]
You have to use the api-v1 branch if you need to backup a password-protected blog

**Comment by WyohKnott** [comment]
Private blogs != password protected blogs.

Private blogs are blogs which are visible only for logged users, and they are only displayed in the "sidebar view" (in dash view).

Blogs which has been made private can't be reached by the api v1 either, nor by RSS.
