### ISSUE TITLE
tumblr_backup.py: exit(0) on success, even if no posts were backed up

### ISSUE THREAD

**Issue by wjt** [bbolli/tumblr-utils#79]
At present, tumblr_backup.py calls `sys.exit(1)` if no posts were backed up. This is inconvenient running an hourly incremental backup from a cronjob, as suggested in `tumblr_backup.md`: I want to receive failure emails when an actual error occurs, but not because I haven't blogged in the past hour (which is true ≥23 hours a day).

I was going to suggest a little tweak to `exit(0)` in incremental mode provided no other error occurs, but since errors (eg 404 when the blog doesn't exist) aren't really propagated out from `TumblrBackup.backup(account)` except in the form of not increasing `total_count` this would need a bit more thought to reliably `exit(1)` when something has genuinely gone wrong.

**Comment by bbolli** [comment]
Sounds reasonable; I'll see what I can do.

Thanks!

**Comment by wjt** [comment]
You could do something like: in every place where `apiparse()` can return `None`, increment some error counter; and then exit success only if that counter is zero?

**Comment by bbolli** [comment]
In the mean time, you can amend your crontab entry like this to ignore the return code:

    0 * * * * tumblr_backup ... || true
