### ISSUE TITLE
bad character range

### ISSUE THREAD

**Issue by Bl4Cc4t** [bbolli/tumblr-utils#83]
So when I try to backup some tumblr, I get the following as output:
[http://pastebin.com/77yEpryg](http://pastebin.com/77yEpryg)

I’m on OS X 10.9.5. I have the newest Python installed (2.7.12) and followed [this tutorial](https://wolfpaulus.com/journal/mac/installing_python_osx/), since Python via Homebrew didn’t work for me at all.

I don’t know what to do...
Even if it’s an error on my side, I would appreciate some help =)

Greez

**Comment by bbolli** [comment]
Have you tried to run it with the stock Mavericks /usr/bin/python? This version is not too old and should aork as well.

**Comment by Bl4Cc4t** [comment]
same error when run like this: `/usr/bin/python tumblr_backup.py`

**Comment by bbolli** [comment]
So, what's the blog you're trying to backup and what is your local path to the backup folder? I'll try to reproduce this here.

**Comment by Bl4Cc4t** [comment]
I tried to backup `151bitch`, my path is `~/Sites/\[2016-11-19\]\ 151`

**Comment by bbolli** [comment]
Yup, this reproduces here. The reason is you're using square brackets in your path which the Pyhon glob module doesn't seem to like. Remove them from your folder name and the backup works. Feel free to file a bug report for the Python library.

**Comment by Bl4Cc4t** [comment]
Okay, that’s one of the things I would’ve never expected. What the hell...
Anyways, thank you very much for your fast help and also for providing such a tool!
I did backup my blogs before with httrack, but this is way easier. Cheers!

**Comment by bbolli** [comment]
You're welcome!
