### ISSUE TITLE
Some videos aren’t saved properly

### ISSUE THREAD

**Issue by Bl4Cc4t** [bbolli/tumblr-utils#85]
So, when I try to play some of the downloaded videos (hosted by tumblr only), the majority suddenly stops during playtime (at 9-20 seconds).
Also, they tend to have a specific file size; 3.5 MB.
I know that this problem has to do with **youtube-dl**, but maybe I’m missing something here too.
This problem happens with all blogs I’ve backed up so far.
If I can provide any more infos, please let me know.

**Comment by bbolli** [comment]
Is there any error message?

**Comment by Bl4Cc4t** [comment]
No, sorry.
Only some `HTTP Error 403: Forbidden downloading https://vtt.tumblr.com/tumblr_miqpateXCl1rzyv40.mp4`, but that doesn’t help with this I guess :V

**Comment by Hrxn** [comment]
I've seen this one before. Pretty certain that one is on Tumblr's side.

I unfortunately don't have an example link available at the moment, but this error appears when you try to download a video hosted by Tumblr itself which has been removed or made inaccessible otherwise, I think.

You can test this with the corresponding URL to this video, i.e. `<blog-name>.tumblr.com/post/<post-id>` (You can skip the part after the post ID if present).

Try to open that in a browser..

**Comment by Bl4Cc4t** [comment]
@Hrxn 
I don’t think so, since I am certainly able to download them. Not fully, though... =(
Also, I can see them on the blog too.
It’s just dumb to have backed up a blog, but not quite (since the videos are broken).
I just hope this gets fixed somehow.

**Comment by bbolli** [comment]
Can you try to download the video with stand-alone youtube-dl? In other words, does this work:

    youtube-dl <permalink of video-post>

**Comment by Bl4Cc4t** [comment]
Just tested it, it works like a charm.
But your tool seems to use another youtube-dl version, I had to `pip youtube_dl`.
Maybe that has to do with this?

**Comment by bbolli** [comment]
`tumblr_backup` uses whatever version it finds on the Python `sys.path` — it's the user's responsability to update it from time to time.

**Comment by Bl4Cc4t** [comment]
What’ the `sys.path`?
Can I perhaps add something there to make it work like it should?

**Comment by bbolli** [comment]
`sys.path` is Python's list of directories it searches when a program imports a module. You can check it interactively with

    $ python
    Python 2.7.12 (default, Jun 29 2016, 14:04:27)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys, pprint
    >>> pprint.pprint(sys.path)
    ['',
     '/Library/Python/2.7/site-packages/lxml-2.3.4-py2.7-macosx-10.7-intel.egg',
     '/Library/Python/2.7/site-packages/Markdown-2.2.1-py2.7.egg',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
     '/Users/bb/Library/Python/2.7/lib/python/site-packages',
     '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
     '/usr/local/Cellar/protobuf/3.0.2/libexec/lib/python2.7/site-packages',
     '/Library/Python/2.7/site-packages']
    >>>

Your output should look similarly.

To check where Python imports youtube-dl from:

    >>> import youtube_dl
    >>> youtube_dl.__file__
    '/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.1.23-py2.7.egg/youtube_dl/__init__.pyc'
    >>> ^D
    $

**Comment by Bl4Cc4t** [comment]
Okay, my output is
`'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/__init__.pyc'`.
So, how do I edit this to point to the correct youtube-dl directory?
I installed it via `homebrew` if that helps

**Comment by bbolli** [comment]
You can simply update it using pip: `pip install -U youtube-dl`

**Comment by Bl4Cc4t** [comment]
Apparently, updating youtube-dl via this command solved the issue for me!
Thank  you for your help =)
(the only bad thing is I already backed up some blogs...)
<img width="266" alt="bildschirmfoto 2016-12-24 um 1 40 14" src="https://cloud.githubusercontent.com/assets/6740726/21467018/867cfa76-c9de-11e6-8884-452311e27221.png">

**Comment by Hrxn** [comment]
Oh, look, only 405 GiB.. 😅 

I didn't realize that there even are so many blogs on Tumblr. Might need to investigate further.

Happy Christmas to you as well!

**Comment by bbolli** [comment]
I don't even want to know what you use all these backups for... :-)

Merry Christmas!
