### ISSUE TITLE
Rename extensionless files.

### ISSUE THREAD

**Issue by indrakaw** [bbolli/tumblr-utils#90]
Extensionless files are kinda annoying. Let's `tumblr-utils` rename it automatically.

**Comment by adamamyl** [comment]
👎  I don't find them annoying at all.

**Comment by bbolli** [comment]
What files are you talking about?

**Comment by indrakaw** [comment]
@adamamyl okay.
@bbolli File images.

**Comment by bbolli** [comment]
I need an example blog where this occurs. There's already a mechanism build in that renames extensionless image files: see https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup.py#L813
