### ISSUE TITLE
Archiving with OAuth

### ISSUE THREAD

**Issue by jtvjan** [bbolli/tumblr-utils#95]
For NSFW blogs, you now need to authenticate with OAuth and disable the filter on that account. Try using the [API Console](https://api.tumblr.com/console/calls/blog/posts). If you try to get the post list on an NSFW blog using only your API Key, you get a 404, but if you use OAuth, it gives you the post list like normal.

**Comment by Cebtenzzre** [comment]
Is this still applicable?  I haven't needed OAuth for NSFW blogs.  Dashboard-only blogs are another story.

**Comment by Hrxn** [comment]
Well, it's still applicable, I'd say. But still a duplicate of #128 .
I assume that private/"Dashboard-only" NSFW blogs is what the opener meant.

**Comment by jtvjan** [comment]
When I first tried this script it didn't want to download NSFW blogs and I assumed you had to auth with an account to access them. Accessing NSFW blogs after to removal probably does actually need authentication as I'm still able to view them through the Tumblr app. Maybe that uses the svc api? Closing this as it's a duplicate of #128.
